import { IAutoTaskAssemblerTest } from '../tests.interface';

/**
 * Automated tests for the task assembler
 */
export const AUTO_TASK_ASSEMBLER_TESTS: IAutoTaskAssemblerTest[] = [
  {
    suiteName: `Verify keyword formatting for ENVITasks`,
    fileName: `envitask.keywords1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "input_raster",`,
          `      "name": "input_raster",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "keyword": "output_raster_uri",`,
          `      "name": "output_raster_uri",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "keyword": "output_raster",`,
          `      "name": "output_raster",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "INPUT_RASTER",`,
          `      "name": "input_raster",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "keyword": "OUTPUT_RASTER_URI",`,
          `      "name": "output_raster_uri",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "keyword": "OUTPUT_RASTER",`,
          `      "name": "output_raster",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "INPUT_RASTER",`,
          `      "name": "input_raster",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "keyword": "output_RASTER_uri",`,
          `      "name": "output_raster_uri",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "keyword": "OUTPUT_RASTER",`,
          `      "name": "output_raster",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify parameter formatting for ENVI Tasks`,
    fileName: `envitask.parameters1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "input_raster",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "output_raster_uri",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": "output_raster",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_RASTER_URI",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_RASTER",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "input_raster  ",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "  output_raster_uri ",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": " OUTPUT_RASTER  ",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify direction formatting for ENVI Tasks`,
    fileName: `envitask.direction1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "  ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "input_raster",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "output_raster_uri",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "input",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": "output_raster",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "output",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'upper',
          },
        },
      },
      {
        name: `lower case`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection  ",`,
          `  "description": " Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_RASTER_URI",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "INPUT",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_RASTER",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "OUTPUT",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "ATAnomalyDetection",`,
          `  "schema": "envitask_3.3",`,
          `  "base_class": "ENVITaskFromProcedure",`,
          `  "routine": "atAnomalyDetection",`,
          `  "display_name": "AT Anomaly Detection",`,
          `  "description": "Runs an automated anomaly detection using the Anomaly Detection workflow from ENVI Desktop.",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "input_raster  ",`,
          `      "display_name": "Input Raster",`,
          `      "description": "The raster to run anomaly detection on.",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster"`,
          `    },`,
          `    {`,
          `      "name": "  output_raster_uri ",`,
          `      "display_name": "Output Raster URI",`,
          `      "description": "Specify a string with the fully-qualified path and filename for OUTPUT_RASTER.",`,
          `      "direction": "INPUT",`,
          `      "required": false,`,
          `      "hidden": false,`,
          `      "type": "ENVIURI",`,
          `      "auto_extension": ".dat"`,
          `    },`,
          `    {`,
          `      "name": " OUTPUT_RASTER  ",`,
          `      "display_name": "Output Raster",`,
          `      "description": "This is a reference to an ENVIRaster object.",`,
          `      "direction": "OUTPUT",`,
          `      "required": true,`,
          `      "hidden": false,`,
          `      "type": "ENVIRaster",`,
          `      "uri_param": "OUTPUT_RASTER_URI"`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify keyword formatting for ENVI Task Legacy`,
    fileName: `envitask-legacy.keywords1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "input_raster",`,
          `      "name": "input_raster",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "keyword": "input_ecf_report_uri",`,
          `      "name": "input_ecf_report_uri",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "keyword": "output_roi",`,
          `      "name": "output_roi",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "INPUT_RASTER",`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "keyword": "INPUT_EFC_REPORT_FILE",`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "keyword": "OUTPUT_ROI",`,
          `      "name": "OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "input_RASTER",`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "keyword": "INPUT_EFC_REPORT_FILE",`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "keyword": "OUTPUT_ROI",`,
          `      "name": "OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify parameter formatting for ENVI Task Legacy`,
    fileName: `envitask-legacy.parameters1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "input_raster",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "input_ecf_report_uri",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "output_roi",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "  mlEFCReportToROI",`,
          `  "displayName": " ML EFC Report to ROI",`,
          `  "description": "  This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "  INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "  ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "output_roi  ",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify direction formatting for ENVI Task Legacy`,
    fileName: `envitask-legacy.direction-and-req1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "  OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "  ENVIROI",`,
          `      "direction": "output",`,
          `      "parameterType": "required",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3"   ,`,
          `  "parameters":   [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "INPUT",`,
          `      "parameterType": "REQUIRED",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "INPUT",`,
          `      "parameterType": "REQUIRED",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "OUTPUT",`,
          `      "parameterType": "REQUIRED",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "MLEFCReportToROI",`,
          `  "baseClass": "ENVITaskFromProcedure",`,
          `  "routine": "mlEFCReportToROI",`,
          `  "displayName": "ML EFC Report to ROI",`,
          `  "description": "This task will convert an ENVI Feature Counting (EFC) report file to an ROI for use with the new and improved chip to points. The class anmes must start with positive or negative (case insensitive). You don't have to have both present, but you cannot have mor than two classes.",`,
          `  "version": "5.3",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "INPUT_RASTER",`,
          `      "displayName": "Training Data Source Raster",`,
          `      "dataType": "ENVIRASTER",`,
          `      "direction": "INPUT",`,
          `      "parameterType": "REQUIRED",`,
          `      "description": "Specify the original raster that was used to find training data."`,
          `    },`,
          `    {`,
          `      "name": "INPUT_EFC_REPORT_FILE",`,
          `      "displayName": "EFC Report File",`,
          `      "dataType": "ENVIURI",`,
          `      "direction": "input",`,
          `      "parameterType": "required",`,
          `      "description": "Specify the ENVI Feature Counting report file (must have a .txt extension)."`,
          `    },`,
          `    {`,
          `      "name": "OUTPUT_ROI",`,
          `      "displayName": "Output ROI",`,
          `      "dataType": "ENVIROI",`,
          `      "direction": "OUTPUT",`,
          `      "parameterType": "REQUIRED",`,
          `      "description": "The output ROI file that will contain the pixel locations of our training data."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify keyword formatting for IDL Tasks`,
    fileName: `idltask.keywords1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "s3_url",`,
          `      "name": "s3_url",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "keyword": "local_file",`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "S3_URL",`,
          `      "name": "S3_URL",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "keyword": "LOCAL_FILE",`,
          `      "name": "LOCAL_FILE",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "keyword": "S3_url",`,
          `      "name": "S3_URL",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "keyword": "local_FILE",`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            keywords: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify parameter formatting for IDL Tasks`,
    fileName: `idltask.parameters1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "s3_url",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "S3_URL",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "LOCAL_FILE",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "S3_URL",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            properties: 'none',
          },
        },
      },
    ],
  },
  {
    suiteName: `Verify direction formatting for IDL Tasks`,
    fileName: `idltask.direction1.spec.ts`,
    tests: [
      {
        name: `upper case`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "s3_url",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'upper',
          },
        },
      },
      {
        name: `lower`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "s3_url",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'lower',
          },
        },
      },
      {
        name: `ignore`,
        code: [
          `{`,
          `  "name": "Download_S3_URL",`,
          `  "base_class": "IDLTaskFromProcedure",`,
          `  "routine": "download_S3_URL",`,
          `  "display_name": "Download S3 URL",`,
          `  "description": "This task downloads a resource specified by an S3 URL into a local file.",`,
          `  "revision": "1.0.0",`,
          `  "schema": "idltask_1.1",`,
          `  "parameters": [`,
          `    {`,
          `      "name": "s3_url",`,
          `      "display_name": "S3 URL",`,
          `      "type": "String",`,
          `      "direction": "INPUT",`,
          `      "required": true,`,
          `      "description": "The S3 URL to download.  This must use the HTTP[S] scheme, not S3 scheme."`,
          `    },`,
          `    {`,
          `      "name": "local_file",`,
          `      "display_name": "Local Filename",`,
          `      "type": "String",`,
          `      "direction": "input",`,
          `      "required": true,`,
          `      "description": "The local file in which to download the S3 resource."`,
          `    }`,
          `  ]`,
          `}`,
        ],
        config: {
          style: {
            control: 'none',
          },
        },
      },
    ],
  },
];
