import { IDL_TYPE_LOOKUP } from './idl-data-types.interface';

/**
 * Map, for convenience, with known IDL data types
 */
export const KNOWN_IDL_TYPES: { [key: string]: any } = {};
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.COMPLEX_NUMBER] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.COMPLEX_DOUBLE] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.COMPLEX_FLOAT] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.NUMBER] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.BIG_INTEGER] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.DOUBLE] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.FLOAT] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.UNSIGNED_LONG64] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.LONG64] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.UNSIGNED_LONG] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.LONG] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.UNSIGNED_INTEGER] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.INTEGER] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.BYTE] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.STRING] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.ARRAY] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.HASH] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.ORDERED_HASH] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.DICTIONARY] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.LIST] = true;
KNOWN_IDL_TYPES[IDL_TYPE_LOOKUP.POINTER] = true;
