import { GetExtensionPath } from '@idl/idl/files';
import { ResetGlobalDisplayNames } from '@idl/parsing/index';
import { LoadTask } from '@idl/schemas/tasks';
import { IGlobalsToTrack, TaskToGlobalToken } from '@idl/types/tasks';

describe(`[auto generated] Correctly parse task file`, () => {
  it(`[auto generated] envi`, async () => {
    // specify reference filepath
    const filepath = GetExtensionPath(
      'idl/test/task-parsing/ExportRasterToCADRG.task'
    );

    // reset global display names
    ResetGlobalDisplayNames();

    // load our task
    const task = await LoadTask(filepath);

    // define expected local variables
    const expected: IGlobalsToTrack = {
      function: {
        type: 'f',
        name: 'enviexportrastertocadrgtask',
        pos: [0, 0, 0],
        meta: {
          display: 'ENVIExportRasterToCADRGTask',
          source: 'user',
          docs: "\nThis task exports a 3-band, byte image to the CADRG format.\n\n### Syntax\n\n```idl\n;+\n; :Returns: ENVITask<ExportRasterToCADRG>\n;-\nmyTask = ENVITask('ExportRasterToCADRG')\n\n; set input parameters\nmyTask.input_raster = value\nmyTask.scale = value\nmyTask.classification = value\nmyTask.producer_code = value\nmyTask.release_code = value\nmyTask.country_code = value\nmyTask.originating_station_id = value\nmyTask.originator_name = value\nmyTask.output_directory = value\n\n; run the task\nmyTask.execute\n\n; get output parameters\noutput_raster = myTask.output_raster\n\n```\n\n\n### Input Parameters\n\n- **input_raster**: ENVIRaster\n\n  Specify a 3-band, byte raster to export to the CADRG format.\n\n- **scale**: '1:5,000,000 GNC Charts (754m)' | '1:2,000,000 JNC Charts (300m)' | '1:1,000,000 ONC Charts (150m)' | '1:500,000 TPC Charts (75m)' | '1:250,000 JOG Charts (37.5m)' | '1:250,000 JOG-A Charts (37.5m)' | '1:100,000 TLM Charts (15m)' | '1:50,000 TLM Charts (7.5m)' | '1:25,000 City Graphics (3.75m)' | '1:12,500 City Graphics (1.88m)' | '1:10,000 City Graphics (1.5m)'\n\n  Specify the scale of the CADRG files.\n\n- **classification**: 'Unclassified' | 'Restricted' | 'Confidential' | 'Secret' | 'Top Secret'\n\n  Specify the classification level of the CADRG files.\n\n- **producer_code**: 'Non-specified, Imagery formatted to RPF' | 'Air Force Air Combat Command' | 'Air Force Electronic Systems Center' | 'National Imagery and Mapping Agency, Primary' | 'NIMA, Alternate Site 1' | 'NIMA, Alternate Site 2' | 'NIMA, Alternate Site 3' | 'Air Force Special Operations Command' | 'United States Special Operations Command' | 'Pacific Air Forces' | 'United States Air Force, Europe' | 'US producer outside the Department of Defense' | 'Non-US producer' | 'NIMA produced Digital CHUM file' | 'DoD producer of Digital CHUM file other than NIMA' | 'Non-US (foreign) producer of Digital CHUM files' | 'US producer of Digital CHUM files outside DoD'\n\n  Specify the producer code of the CADRG files.\n\n- **release_code**: 'None' | 'ATOMAL (NATO designation to identify restricted or formerly restricted data)' | 'Background use only' | 'Caution - Proprietary information involved (PROPIN)' | 'Continued Control' | 'Copyright' | 'COSMIC (Caveat applied to NATO Top Secret)' | 'Critical Nuclear Weapon Design Information/DoD directive 5210.2 applies (CNWDI)' | 'Cryptographic (CRYPTO)' | 'Dissemination and Extraction Of information controlled by originator (ORCON)' | 'Distribution Limited-Destroy when no longer needed (DIST LIM)' | 'Encrypted for Transmission Only' | 'For Official Use Only (FOUO)' | 'Formerly restricted data (FRD)' | 'Intelligence Components Only' | 'Limited' | 'Limited official use' | 'NFIB (National Foreign Intelligence Board) departments only (NFIB ONLY)' | 'No Dissemination Abroad' | 'Noncompartmented' | 'Not releasable to contractors/consultants' | 'Not releasable to foreign national (DoD)' | 'Not releasable to foreign nationals (NOFORN)' | 'NSC Participating Agencies Only' | 'Personal Data - Privacy Act' | 'Releasable to Republic of Vietnam' | 'Restricted Data (RD)' | 'SAO' | 'SAO Handling Caveat #1 (SAO-1)' | 'SAO Handling Caveat #2 (SAO-2)' | 'SAO Handling Caveat #3 (SAO-3)' | 'SAO Special Intelligence Handling Caveat #2 (SAO-SI-2)' | 'SAO Special Intelligence Handling Caveat #3 (SAO-SI-3)' | 'SAO Special Intelligence Handling Caveat #4 (SAO-SI-4)' | 'Single Integrated Operational Plan (SIOP)' | 'Single Integrated Operational Plan/Extremely Sensitive Information (SIOP/ESI)' | 'Special Control' | 'Special Handling Required/Not Releasable to foreign Nationals' | 'Special Intelligence (SI)' | 'Special Intelligence Handling Caveat #l (SI-1)' | 'Authorized for release to Australia (REL AUSTRALIA)' | 'Authorized for release to Canada (REL CANADA)' | 'This information has been authorized for release to CENTO (REL CENTO)' | 'Authorized for release to Chile (REL CHILE)' | 'Authorized for release to Denmark (REL DENMARK)' | 'Authorized for release to Federal Republic of Germany (FEDERAL REPUBLIC OF GERMANY)' | 'Authorized for release to France (REL FRANCE)' | 'Authorized for release to Greece (REL GREECE)' | 'Authorized for release to Israel (REL ISRAEL)' | 'Authorized for release to Italy (REL ITALY)' | 'Authorized for release to Japan (REL JAPAN)' | 'Authorized for release to Jordan (REL JORDAN)' | 'Authorized for release to NATO (REL NATO)' | 'Authorized for release to NATO Forces (REL NATO FORCES)' | 'Authorized for release to New Zealand (REL NEW ZEALAND)' | 'Authorized for release to Norway (REL NORWAY)' | 'Authorized for release to Taiwan (REL TAIWAN)' | 'Authorized for release to Republic of Korea (REL REPUBLIC OF KOREA)' | 'This Information has been Authorized for release to SEATO (REL SEATO)' | 'Authorized for release to Denmark' | 'Authorized for release to Spain (REL SPAIN)' | 'Authorized for release to Sweden (REL SWEDEN)' | 'Authorized for release to Thailand (REL THAILAND)' | 'Authorized for release to Turkey (REL TURKEY)' | 'Authorized for release to United Kingdom (REL UNITED KINGDOM)' | 'Warning Notice - Intelligence sources or Methods Involved (WNINTEL)'\n\n  Specify the release code of the CADRG files.\n\n- **country_code**: 'None' | 'Abu Musa (Disputed Island In Persian Gulf)' | 'Afghanistan' | 'Albania' | 'Algeria' | 'American Samoa (US)' | 'Andaman Islands (IN)' | 'Andorra' | 'Angola' | 'Anquilla (Leeward Islands) (UK)' | 'Annobon (Pagulu) (EK)' | 'Antarctica' | 'Antigua-Barbuda' | 'Argentina' | 'Armenia' | 'Aruba (NL)' | 'Ashmore & Cartier Islands (AS)' | 'Australia' | 'Austria' | 'Azerbaijan' | 'Azores (PO)' | 'Bahama Islands' | 'Bahrain' | 'Baker Islands (SP)' | 'Bangladesh' | 'Barbados' | 'Bassas Da India (FR)' | 'Belarus' | 'Belgium' | 'Belize' | 'Benin' | 'Bermuda' | 'Bhutan' | 'Bolivia' | 'Bosnia-Herzegovina' | 'Botswana' | 'Bovet Island (NO)' | 'Brazil' | 'British Indian Ocean Territory (Chagos Archipelago)' | 'British Virgin Islands (Leeward Islands)' | 'Brunei' | 'Bulgaria' | 'Burkina Faso (Upper Volta)' | 'Myanmar (Burma)' | 'Burundi' | 'Cabinda (AO)' | 'Kampuchea (Cambodia)' | 'Cameroon' | 'Canada' | 'Canary Islands (SP)' | 'Cape Verde Islands' | 'Caroline Islands' | 'Cayman Islands' | 'Central African Republic' | 'Chad' | 'Chile' | 'China, People's Republic of' | 'Christmas Island (Indian Ocean) (AS)' | 'Clipperton Island (FR)' | 'Cocos Islands (Keeling) (AS)' | 'Columbia' | 'Comoro Islands (AS)' | 'Congo' | 'Cook Islands (NZ)' | 'Coral Sea Islands (AS)' | 'Costa Rica' | 'Cote d?Ivoire (Ivory Coast)' | 'Crete (Kriti) (GR)' | 'Croatia' | 'Cuba' | 'Cyprus' | 'Czech Republic' | 'Denmark' | 'Diego Garcia' | 'Djibouti' | 'Dominica' | 'Dominican Republic' | 'Easter Island (Isla De Pascua) (CI)' | 'Equador' | 'Egypt' | 'El Salvador' | 'Elobey, Islas De' | 'Equatorial Guinea' | 'Eritrea' | 'Estonia' | 'Ethiopia' | 'Europa Island (FR)' | 'Farroe Islands (DE)' | 'Falkland Islands (UK) (Malvinas)' | 'Fiji Islands' | 'Finland' | 'France' | 'French Guiana' | 'French Polynesia' | 'French Southern & Antarctic Lands' | 'Gabon' | 'Gambia' | 'Gaza Strip (Is)' | 'Georgia' | 'Germany' | 'Ghana' | 'Gibraltar (UK)' | 'Glorioso Island (Ma)' | 'Greece' | 'Greenland' | 'Grenada' | 'Guadeloupe (Leeward Islands)' | 'Guam' | 'Guatemala' | 'Guernsey (UK)' | 'Guinea' | 'Guinea-Bissau' | 'Guyana' | 'Haiti' | 'Heard Island & McDonald Is (AS)' | 'Honduras' | 'Hong Kong (UK)' | 'Howland Island (US)' | 'Hungary' | 'Iceland' | 'India' | 'Indonesia' | 'Iran' | 'Iraq' | 'Ireland' | 'Israel' | 'Italy' | 'Jamaica' | 'Jan Mayen Is (NO)' | 'Japan' | 'Jarvis Island (US)' | 'Jersey (UK)' | 'Johnston Atoll (US)' | 'Jordan' | 'Juan De Nova Islands (FR)' | 'Juan Fernandez' | 'Kazakhstan' | 'Kenya' | 'Kingman Reef (US)' | 'Korea, North' | 'Korea, South' | 'Kuwait' | 'Kirghizia' | 'Lakshadweep Islands (IN)' | 'Laos' | 'Latvia' | 'Lebanon' | 'Lesotho' | 'Liberia' | 'Libya' | 'Liechtenstein' | 'Lithuania' | 'Luxembourg' | 'Macao (PO)' | 'Macedonia' | 'Macais Nguema Biyogo' | 'Madagascar' | 'Madeira Islands (PO)' | 'Malawi' | 'Malaysia' | 'Maldives' | 'Mali' | 'Malta' | 'Isle of Man (UK)' | 'Republic of the Marshall Islands' | 'Martinique (FR)' | 'Mauritania' | 'Mauritius' | 'Mayotte (FR)' | 'Mexico' | 'Federated States of Micronesia' | 'Midway Island (US)' | 'Moldova' | 'Monaco' | 'Mongolia' | 'Montenegro' | 'Montserrat' | 'Morocco' | 'Mozambique' | 'Namibia' | 'Nauru' | 'Navassa Island (US)' | 'Nepal' | 'Netherlands' | 'Netherlands Antilles' | 'New Caledonia (FR)' | 'New Zealand' | 'Nicaragua' | 'Nicobar Islands (IN)' | 'Niger' | 'Nigeria' | 'Niue (NZ)' | 'Norfolk Islands (AS)' | 'Northern Ireland' | 'Northern Mariana Islands (US)' | 'Norway' | 'Okinawa (JA)' | 'Oman' | 'Pakistan' | 'Palau, Republic of (US)' | 'Palmyra Atoll (US)' | 'Panama' | 'Papua New Guinea' | 'Paracel Islands (CH)' | 'Paraguay' | 'Pemba Island (TZ)' | 'Peru' | 'Philippines' | 'Pitcairn Island (UK)' | 'Poland' | 'Portugal' | 'Puerto Rico (US)' | 'Qatar' | 'Reunion (FR)' | 'Romania' | 'Russia' | 'Rwanda' | 'Saint Helena' | 'Saint Lucia' | 'Saint Vincent and the Grenadines' | 'Sala Y Gomez (CI)' | 'San Ambrosia Island (CI)' | 'San Felix Island (CI)' | 'San Marino' | 'Sao Tome and Principe' | 'Sardinia (IT)' | 'Saudi Arabia' | 'Senegal' | 'Serbia' | 'Seychelles' | 'Sierra Leone' | 'Singapore' | 'Slovakia' | 'Slovenia' | 'Socotra (YM)' | 'Solomon Islands' | 'Somalia' | 'Republic of South Africa' | 'South Georgia & South Sandwich Is (UK)' | 'South Orkney Islands (UK)' | 'South Shetland Islands (UK)' | 'Spain' | 'Spratly Islands  (CH, RP, MY, VM)' | 'Sri Lanka' | 'St. Christopher-Nevis' | 'St. Pierre Miqurlon (CA)' | 'Sudan' | 'Surinam' | 'Svalbard (NO)' | 'Swaziland' | 'Sweden' | 'Switzerland' | 'Syria' | 'Taiwan and Penghu' | 'Tajikistan' | 'Tanzania' | 'Thailand' | 'Togo' | 'Tokelau (NZ)' | 'Tonga Islands' | 'Trinidad and Tobago' | 'Tromelin Island (FR)' | 'Tunisia' | 'Turkey' | 'Turkmenistan' | 'Turks and Caicos Islands (UK)' | 'Tuvalu' | 'Uganda' | 'Ukraine' | 'United Arab Emirates' | 'United Kingdom' | 'United States' | 'US miscellaneous Pacific Islands' | 'Uruguay' | 'Uzbekistan' | 'Vanuatu (Former New Hebrides)' | 'Vatican City' | 'Venezuela' | 'Vietnam' | 'Virgin Islands (US, UK)' | 'Wake Island (US)' | 'Wallis and Futuna Islands (FR)' | 'Walvis Bay (SF)' | 'West Bank' | 'Western Sahara (MO)' | 'Western Samoa' | 'Yemen' | 'Zaire' | 'Zambia' | 'Zanzibar (TZ)' | 'Zimbabwe'\n\n  Specify the country code of the CADRG files.\n\n- **originating_station_id**: String\n\n  Specify the Originating Station ID tag used by NITF.\n\n- **originator_name**: String\n\n  Specify the Originator's Name tag used by NITF.\n\n- **output_directory**: String\n\n  Directory in which the resulting CADRG files will be written.\n\n\n\n### Output Parameters\n\n- **output_raster**: Array\\<ENVIRASTER\\>\n\n  This is an array of one or more rasters produced by the export.\n\n",
          private: false,
          returns: [
            {
              name: 'enviexportrastertocadrgtask',
              display: 'ENVITask<exportrastertocadrg>',
              serialized: 'ENVITask<exportrastertocadrg>',
              args: [
                [
                  {
                    name: 'exportrastertocadrg',
                    display: 'exportrastertocadrg',
                    serialized: 'exportrastertocadrg',
                    args: [],
                    meta: {},
                  },
                ],
              ],
              meta: {},
            },
          ],
          args: {},
          kws: {},
          docsLookup: {},
          struct: [],
        },
      },
      structure: {
        type: 's',
        name: 'enviexportrastertocadrgtask',
        pos: [0, 0, 0],
        meta: {
          display: 'ENVIExportRasterToCADRGTask',
          source: 'user',
          docs: "This task exports a 3-band, byte image to the CADRG format.\n\n\n### Properties\n\n- **input_raster**: ENVIRaster\n\n  Specify a 3-band, byte raster to export to the CADRG format.\n\n- **scale**: '1:5,000,000 GNC Charts (754m)' | '1:2,000,000 JNC Charts (300m)' | '1:1,000,000 ONC Charts (150m)' | '1:500,000 TPC Charts (75m)' | '1:250,000 JOG Charts (37.5m)' | '1:250,000 JOG-A Charts (37.5m)' | '1:100,000 TLM Charts (15m)' | '1:50,000 TLM Charts (7.5m)' | '1:25,000 City Graphics (3.75m)' | '1:12,500 City Graphics (1.88m)' | '1:10,000 City Graphics (1.5m)'\n\n  Specify the scale of the CADRG files.\n\n- **classification**: 'Unclassified' | 'Restricted' | 'Confidential' | 'Secret' | 'Top Secret'\n\n  Specify the classification level of the CADRG files.\n\n- **producer_code**: 'Non-specified, Imagery formatted to RPF' | 'Air Force Air Combat Command' | 'Air Force Electronic Systems Center' | 'National Imagery and Mapping Agency, Primary' | 'NIMA, Alternate Site 1' | 'NIMA, Alternate Site 2' | 'NIMA, Alternate Site 3' | 'Air Force Special Operations Command' | 'United States Special Operations Command' | 'Pacific Air Forces' | 'United States Air Force, Europe' | 'US producer outside the Department of Defense' | 'Non-US producer' | 'NIMA produced Digital CHUM file' | 'DoD producer of Digital CHUM file other than NIMA' | 'Non-US (foreign) producer of Digital CHUM files' | 'US producer of Digital CHUM files outside DoD'\n\n  Specify the producer code of the CADRG files.\n\n- **release_code**: 'None' | 'ATOMAL (NATO designation to identify restricted or formerly restricted data)' | 'Background use only' | 'Caution - Proprietary information involved (PROPIN)' | 'Continued Control' | 'Copyright' | 'COSMIC (Caveat applied to NATO Top Secret)' | 'Critical Nuclear Weapon Design Information/DoD directive 5210.2 applies (CNWDI)' | 'Cryptographic (CRYPTO)' | 'Dissemination and Extraction Of information controlled by originator (ORCON)' | 'Distribution Limited-Destroy when no longer needed (DIST LIM)' | 'Encrypted for Transmission Only' | 'For Official Use Only (FOUO)' | 'Formerly restricted data (FRD)' | 'Intelligence Components Only' | 'Limited' | 'Limited official use' | 'NFIB (National Foreign Intelligence Board) departments only (NFIB ONLY)' | 'No Dissemination Abroad' | 'Noncompartmented' | 'Not releasable to contractors/consultants' | 'Not releasable to foreign national (DoD)' | 'Not releasable to foreign nationals (NOFORN)' | 'NSC Participating Agencies Only' | 'Personal Data - Privacy Act' | 'Releasable to Republic of Vietnam' | 'Restricted Data (RD)' | 'SAO' | 'SAO Handling Caveat #1 (SAO-1)' | 'SAO Handling Caveat #2 (SAO-2)' | 'SAO Handling Caveat #3 (SAO-3)' | 'SAO Special Intelligence Handling Caveat #2 (SAO-SI-2)' | 'SAO Special Intelligence Handling Caveat #3 (SAO-SI-3)' | 'SAO Special Intelligence Handling Caveat #4 (SAO-SI-4)' | 'Single Integrated Operational Plan (SIOP)' | 'Single Integrated Operational Plan/Extremely Sensitive Information (SIOP/ESI)' | 'Special Control' | 'Special Handling Required/Not Releasable to foreign Nationals' | 'Special Intelligence (SI)' | 'Special Intelligence Handling Caveat #l (SI-1)' | 'Authorized for release to Australia (REL AUSTRALIA)' | 'Authorized for release to Canada (REL CANADA)' | 'This information has been authorized for release to CENTO (REL CENTO)' | 'Authorized for release to Chile (REL CHILE)' | 'Authorized for release to Denmark (REL DENMARK)' | 'Authorized for release to Federal Republic of Germany (FEDERAL REPUBLIC OF GERMANY)' | 'Authorized for release to France (REL FRANCE)' | 'Authorized for release to Greece (REL GREECE)' | 'Authorized for release to Israel (REL ISRAEL)' | 'Authorized for release to Italy (REL ITALY)' | 'Authorized for release to Japan (REL JAPAN)' | 'Authorized for release to Jordan (REL JORDAN)' | 'Authorized for release to NATO (REL NATO)' | 'Authorized for release to NATO Forces (REL NATO FORCES)' | 'Authorized for release to New Zealand (REL NEW ZEALAND)' | 'Authorized for release to Norway (REL NORWAY)' | 'Authorized for release to Taiwan (REL TAIWAN)' | 'Authorized for release to Republic of Korea (REL REPUBLIC OF KOREA)' | 'This Information has been Authorized for release to SEATO (REL SEATO)' | 'Authorized for release to Denmark' | 'Authorized for release to Spain (REL SPAIN)' | 'Authorized for release to Sweden (REL SWEDEN)' | 'Authorized for release to Thailand (REL THAILAND)' | 'Authorized for release to Turkey (REL TURKEY)' | 'Authorized for release to United Kingdom (REL UNITED KINGDOM)' | 'Warning Notice - Intelligence sources or Methods Involved (WNINTEL)'\n\n  Specify the release code of the CADRG files.\n\n- **country_code**: 'None' | 'Abu Musa (Disputed Island In Persian Gulf)' | 'Afghanistan' | 'Albania' | 'Algeria' | 'American Samoa (US)' | 'Andaman Islands (IN)' | 'Andorra' | 'Angola' | 'Anquilla (Leeward Islands) (UK)' | 'Annobon (Pagulu) (EK)' | 'Antarctica' | 'Antigua-Barbuda' | 'Argentina' | 'Armenia' | 'Aruba (NL)' | 'Ashmore & Cartier Islands (AS)' | 'Australia' | 'Austria' | 'Azerbaijan' | 'Azores (PO)' | 'Bahama Islands' | 'Bahrain' | 'Baker Islands (SP)' | 'Bangladesh' | 'Barbados' | 'Bassas Da India (FR)' | 'Belarus' | 'Belgium' | 'Belize' | 'Benin' | 'Bermuda' | 'Bhutan' | 'Bolivia' | 'Bosnia-Herzegovina' | 'Botswana' | 'Bovet Island (NO)' | 'Brazil' | 'British Indian Ocean Territory (Chagos Archipelago)' | 'British Virgin Islands (Leeward Islands)' | 'Brunei' | 'Bulgaria' | 'Burkina Faso (Upper Volta)' | 'Myanmar (Burma)' | 'Burundi' | 'Cabinda (AO)' | 'Kampuchea (Cambodia)' | 'Cameroon' | 'Canada' | 'Canary Islands (SP)' | 'Cape Verde Islands' | 'Caroline Islands' | 'Cayman Islands' | 'Central African Republic' | 'Chad' | 'Chile' | 'China, People's Republic of' | 'Christmas Island (Indian Ocean) (AS)' | 'Clipperton Island (FR)' | 'Cocos Islands (Keeling) (AS)' | 'Columbia' | 'Comoro Islands (AS)' | 'Congo' | 'Cook Islands (NZ)' | 'Coral Sea Islands (AS)' | 'Costa Rica' | 'Cote d?Ivoire (Ivory Coast)' | 'Crete (Kriti) (GR)' | 'Croatia' | 'Cuba' | 'Cyprus' | 'Czech Republic' | 'Denmark' | 'Diego Garcia' | 'Djibouti' | 'Dominica' | 'Dominican Republic' | 'Easter Island (Isla De Pascua) (CI)' | 'Equador' | 'Egypt' | 'El Salvador' | 'Elobey, Islas De' | 'Equatorial Guinea' | 'Eritrea' | 'Estonia' | 'Ethiopia' | 'Europa Island (FR)' | 'Farroe Islands (DE)' | 'Falkland Islands (UK) (Malvinas)' | 'Fiji Islands' | 'Finland' | 'France' | 'French Guiana' | 'French Polynesia' | 'French Southern & Antarctic Lands' | 'Gabon' | 'Gambia' | 'Gaza Strip (Is)' | 'Georgia' | 'Germany' | 'Ghana' | 'Gibraltar (UK)' | 'Glorioso Island (Ma)' | 'Greece' | 'Greenland' | 'Grenada' | 'Guadeloupe (Leeward Islands)' | 'Guam' | 'Guatemala' | 'Guernsey (UK)' | 'Guinea' | 'Guinea-Bissau' | 'Guyana' | 'Haiti' | 'Heard Island & McDonald Is (AS)' | 'Honduras' | 'Hong Kong (UK)' | 'Howland Island (US)' | 'Hungary' | 'Iceland' | 'India' | 'Indonesia' | 'Iran' | 'Iraq' | 'Ireland' | 'Israel' | 'Italy' | 'Jamaica' | 'Jan Mayen Is (NO)' | 'Japan' | 'Jarvis Island (US)' | 'Jersey (UK)' | 'Johnston Atoll (US)' | 'Jordan' | 'Juan De Nova Islands (FR)' | 'Juan Fernandez' | 'Kazakhstan' | 'Kenya' | 'Kingman Reef (US)' | 'Korea, North' | 'Korea, South' | 'Kuwait' | 'Kirghizia' | 'Lakshadweep Islands (IN)' | 'Laos' | 'Latvia' | 'Lebanon' | 'Lesotho' | 'Liberia' | 'Libya' | 'Liechtenstein' | 'Lithuania' | 'Luxembourg' | 'Macao (PO)' | 'Macedonia' | 'Macais Nguema Biyogo' | 'Madagascar' | 'Madeira Islands (PO)' | 'Malawi' | 'Malaysia' | 'Maldives' | 'Mali' | 'Malta' | 'Isle of Man (UK)' | 'Republic of the Marshall Islands' | 'Martinique (FR)' | 'Mauritania' | 'Mauritius' | 'Mayotte (FR)' | 'Mexico' | 'Federated States of Micronesia' | 'Midway Island (US)' | 'Moldova' | 'Monaco' | 'Mongolia' | 'Montenegro' | 'Montserrat' | 'Morocco' | 'Mozambique' | 'Namibia' | 'Nauru' | 'Navassa Island (US)' | 'Nepal' | 'Netherlands' | 'Netherlands Antilles' | 'New Caledonia (FR)' | 'New Zealand' | 'Nicaragua' | 'Nicobar Islands (IN)' | 'Niger' | 'Nigeria' | 'Niue (NZ)' | 'Norfolk Islands (AS)' | 'Northern Ireland' | 'Northern Mariana Islands (US)' | 'Norway' | 'Okinawa (JA)' | 'Oman' | 'Pakistan' | 'Palau, Republic of (US)' | 'Palmyra Atoll (US)' | 'Panama' | 'Papua New Guinea' | 'Paracel Islands (CH)' | 'Paraguay' | 'Pemba Island (TZ)' | 'Peru' | 'Philippines' | 'Pitcairn Island (UK)' | 'Poland' | 'Portugal' | 'Puerto Rico (US)' | 'Qatar' | 'Reunion (FR)' | 'Romania' | 'Russia' | 'Rwanda' | 'Saint Helena' | 'Saint Lucia' | 'Saint Vincent and the Grenadines' | 'Sala Y Gomez (CI)' | 'San Ambrosia Island (CI)' | 'San Felix Island (CI)' | 'San Marino' | 'Sao Tome and Principe' | 'Sardinia (IT)' | 'Saudi Arabia' | 'Senegal' | 'Serbia' | 'Seychelles' | 'Sierra Leone' | 'Singapore' | 'Slovakia' | 'Slovenia' | 'Socotra (YM)' | 'Solomon Islands' | 'Somalia' | 'Republic of South Africa' | 'South Georgia & South Sandwich Is (UK)' | 'South Orkney Islands (UK)' | 'South Shetland Islands (UK)' | 'Spain' | 'Spratly Islands  (CH, RP, MY, VM)' | 'Sri Lanka' | 'St. Christopher-Nevis' | 'St. Pierre Miqurlon (CA)' | 'Sudan' | 'Surinam' | 'Svalbard (NO)' | 'Swaziland' | 'Sweden' | 'Switzerland' | 'Syria' | 'Taiwan and Penghu' | 'Tajikistan' | 'Tanzania' | 'Thailand' | 'Togo' | 'Tokelau (NZ)' | 'Tonga Islands' | 'Trinidad and Tobago' | 'Tromelin Island (FR)' | 'Tunisia' | 'Turkey' | 'Turkmenistan' | 'Turks and Caicos Islands (UK)' | 'Tuvalu' | 'Uganda' | 'Ukraine' | 'United Arab Emirates' | 'United Kingdom' | 'United States' | 'US miscellaneous Pacific Islands' | 'Uruguay' | 'Uzbekistan' | 'Vanuatu (Former New Hebrides)' | 'Vatican City' | 'Venezuela' | 'Vietnam' | 'Virgin Islands (US, UK)' | 'Wake Island (US)' | 'Wallis and Futuna Islands (FR)' | 'Walvis Bay (SF)' | 'West Bank' | 'Western Sahara (MO)' | 'Western Samoa' | 'Yemen' | 'Zaire' | 'Zambia' | 'Zanzibar (TZ)' | 'Zimbabwe'\n\n  Specify the country code of the CADRG files.\n\n- **originating_station_id**: String\n\n  Specify the Originating Station ID tag used by NITF.\n\n- **originator_name**: String\n\n  Specify the Originator's Name tag used by NITF.\n\n- **output_directory**: String\n\n  Directory in which the resulting CADRG files will be written.\n\n- **output_raster**: Array\\<ENVIRASTER\\>\n\n  This is an array of one or more rasters produced by the export.\n\n",
          private: false,
          inherits: ['envitask'],
          docsLookup: {},
          props: {
            input_raster: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'input_raster',
              docs: 'Specify a 3-band, byte raster to export to the CADRG format.',
              type: [
                {
                  name: 'ENVIRaster',
                  display: 'ENVIRaster',
                  serialized: 'ENVIRaster',
                  args: [],
                  meta: {},
                },
              ],
              req: true,
            },
            scale: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'scale',
              docs: 'Specify the scale of the CADRG files.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized:
                    "'1:5,000,000 GNC Charts (754m)' | '1:2,000,000 JNC Charts (300m)' | '1:1,000,000 ONC Charts (150m)' | '1:500,000 TPC Charts (75m)' | '1:250,000 JOG Charts (37.5m)' | '1:250,000 JOG-A Charts (37.5m)' | '1:100,000 TLM Charts (15m)' | '1:50,000 TLM Charts (7.5m)' | '1:25,000 City Graphics (3.75m)' | '1:12,500 City Graphics (1.88m)' | '1:10,000 City Graphics (1.5m)'",
                  args: [],
                  meta: { default: '1:5,000,000 GNC Charts (754m)' },
                  value: [
                    '1:5,000,000 GNC Charts (754m)',
                    '1:2,000,000 JNC Charts (300m)',
                    '1:1,000,000 ONC Charts (150m)',
                    '1:500,000 TPC Charts (75m)',
                    '1:250,000 JOG Charts (37.5m)',
                    '1:250,000 JOG-A Charts (37.5m)',
                    '1:100,000 TLM Charts (15m)',
                    '1:50,000 TLM Charts (7.5m)',
                    '1:25,000 City Graphics (3.75m)',
                    '1:12,500 City Graphics (1.88m)',
                    '1:10,000 City Graphics (1.5m)',
                  ],
                },
              ],
              req: false,
            },
            classification: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'classification',
              docs: 'Specify the classification level of the CADRG files.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized:
                    "'Unclassified' | 'Restricted' | 'Confidential' | 'Secret' | 'Top Secret'",
                  args: [],
                  meta: { default: 'Unclassified' },
                  value: [
                    'Unclassified',
                    'Restricted',
                    'Confidential',
                    'Secret',
                    'Top Secret',
                  ],
                },
              ],
              req: false,
            },
            producer_code: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'producer_code',
              docs: 'Specify the producer code of the CADRG files.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized:
                    "'Non-specified, Imagery formatted to RPF' | 'Air Force Air Combat Command' | 'Air Force Electronic Systems Center' | 'National Imagery and Mapping Agency, Primary' | 'NIMA, Alternate Site 1' | 'NIMA, Alternate Site 2' | 'NIMA, Alternate Site 3' | 'Air Force Special Operations Command' | 'United States Special Operations Command' | 'Pacific Air Forces' | 'United States Air Force, Europe' | 'US producer outside the Department of Defense' | 'Non-US producer' | 'NIMA produced Digital CHUM file' | 'DoD producer of Digital CHUM file other than NIMA' | 'Non-US (foreign) producer of Digital CHUM files' | 'US producer of Digital CHUM files outside DoD'",
                  args: [],
                  meta: { default: 'Non-specified, Imagery formatted to RPF' },
                  value: [
                    'Non-specified, Imagery formatted to RPF',
                    'Air Force Air Combat Command',
                    'Air Force Electronic Systems Center',
                    'National Imagery and Mapping Agency, Primary',
                    'NIMA, Alternate Site 1',
                    'NIMA, Alternate Site 2',
                    'NIMA, Alternate Site 3',
                    'Air Force Special Operations Command',
                    'United States Special Operations Command',
                    'Pacific Air Forces',
                    'United States Air Force, Europe',
                    'US producer outside the Department of Defense',
                    'Non-US producer',
                    'NIMA produced Digital CHUM file',
                    'DoD producer of Digital CHUM file other than NIMA',
                    'Non-US (foreign) producer of Digital CHUM files',
                    'US producer of Digital CHUM files outside DoD',
                  ],
                },
              ],
              req: false,
            },
            release_code: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'release_code',
              docs: 'Specify the release code of the CADRG files.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized:
                    "'None' | 'ATOMAL (NATO designation to identify restricted or formerly restricted data)' | 'Background use only' | 'Caution - Proprietary information involved (PROPIN)' | 'Continued Control' | 'Copyright' | 'COSMIC (Caveat applied to NATO Top Secret)' | 'Critical Nuclear Weapon Design Information/DoD directive 5210.2 applies (CNWDI)' | 'Cryptographic (CRYPTO)' | 'Dissemination and Extraction Of information controlled by originator (ORCON)' | 'Distribution Limited-Destroy when no longer needed (DIST LIM)' | 'Encrypted for Transmission Only' | 'For Official Use Only (FOUO)' | 'Formerly restricted data (FRD)' | 'Intelligence Components Only' | 'Limited' | 'Limited official use' | 'NFIB (National Foreign Intelligence Board) departments only (NFIB ONLY)' | 'No Dissemination Abroad' | 'Noncompartmented' | 'Not releasable to contractors/consultants' | 'Not releasable to foreign national (DoD)' | 'Not releasable to foreign nationals (NOFORN)' | 'NSC Participating Agencies Only' | 'Personal Data - Privacy Act' | 'Releasable to Republic of Vietnam' | 'Restricted Data (RD)' | 'SAO' | 'SAO Handling Caveat #1 (SAO-1)' | 'SAO Handling Caveat #2 (SAO-2)' | 'SAO Handling Caveat #3 (SAO-3)' | 'SAO Special Intelligence Handling Caveat #2 (SAO-SI-2)' | 'SAO Special Intelligence Handling Caveat #3 (SAO-SI-3)' | 'SAO Special Intelligence Handling Caveat #4 (SAO-SI-4)' | 'Single Integrated Operational Plan (SIOP)' | 'Single Integrated Operational Plan/Extremely Sensitive Information (SIOP/ESI)' | 'Special Control' | 'Special Handling Required/Not Releasable to foreign Nationals' | 'Special Intelligence (SI)' | 'Special Intelligence Handling Caveat #l (SI-1)' | 'Authorized for release to Australia (REL AUSTRALIA)' | 'Authorized for release to Canada (REL CANADA)' | 'This information has been authorized for release to CENTO (REL CENTO)' | 'Authorized for release to Chile (REL CHILE)' | 'Authorized for release to Denmark (REL DENMARK)' | 'Authorized for release to Federal Republic of Germany (FEDERAL REPUBLIC OF GERMANY)' | 'Authorized for release to France (REL FRANCE)' | 'Authorized for release to Greece (REL GREECE)' | 'Authorized for release to Israel (REL ISRAEL)' | 'Authorized for release to Italy (REL ITALY)' | 'Authorized for release to Japan (REL JAPAN)' | 'Authorized for release to Jordan (REL JORDAN)' | 'Authorized for release to NATO (REL NATO)' | 'Authorized for release to NATO Forces (REL NATO FORCES)' | 'Authorized for release to New Zealand (REL NEW ZEALAND)' | 'Authorized for release to Norway (REL NORWAY)' | 'Authorized for release to Taiwan (REL TAIWAN)' | 'Authorized for release to Republic of Korea (REL REPUBLIC OF KOREA)' | 'This Information has been Authorized for release to SEATO (REL SEATO)' | 'Authorized for release to Denmark' | 'Authorized for release to Spain (REL SPAIN)' | 'Authorized for release to Sweden (REL SWEDEN)' | 'Authorized for release to Thailand (REL THAILAND)' | 'Authorized for release to Turkey (REL TURKEY)' | 'Authorized for release to United Kingdom (REL UNITED KINGDOM)' | 'Warning Notice - Intelligence sources or Methods Involved (WNINTEL)'",
                  args: [],
                  meta: { default: 'None' },
                  value: [
                    'None',
                    'ATOMAL (NATO designation to identify restricted or formerly restricted data)',
                    'Background use only',
                    'Caution - Proprietary information involved (PROPIN)',
                    'Continued Control',
                    'Copyright',
                    'COSMIC (Caveat applied to NATO Top Secret)',
                    'Critical Nuclear Weapon Design Information/DoD directive 5210.2 applies (CNWDI)',
                    'Cryptographic (CRYPTO)',
                    'Dissemination and Extraction Of information controlled by originator (ORCON)',
                    'Distribution Limited-Destroy when no longer needed (DIST LIM)',
                    'Encrypted for Transmission Only',
                    'For Official Use Only (FOUO)',
                    'Formerly restricted data (FRD)',
                    'Intelligence Components Only',
                    'Limited',
                    'Limited official use',
                    'NFIB (National Foreign Intelligence Board) departments only (NFIB ONLY)',
                    'No Dissemination Abroad',
                    'Noncompartmented',
                    'Not releasable to contractors/consultants',
                    'Not releasable to foreign national (DoD)',
                    'Not releasable to foreign nationals (NOFORN)',
                    'NSC Participating Agencies Only',
                    'Personal Data - Privacy Act',
                    'Releasable to Republic of Vietnam',
                    'Restricted Data (RD)',
                    'SAO',
                    'SAO Handling Caveat #1 (SAO-1)',
                    'SAO Handling Caveat #2 (SAO-2)',
                    'SAO Handling Caveat #3 (SAO-3)',
                    'SAO Special Intelligence Handling Caveat #2 (SAO-SI-2)',
                    'SAO Special Intelligence Handling Caveat #3 (SAO-SI-3)',
                    'SAO Special Intelligence Handling Caveat #4 (SAO-SI-4)',
                    'Single Integrated Operational Plan (SIOP)',
                    'Single Integrated Operational Plan/Extremely Sensitive Information (SIOP/ESI)',
                    'Special Control',
                    'Special Handling Required/Not Releasable to foreign Nationals',
                    'Special Intelligence (SI)',
                    'Special Intelligence Handling Caveat #l (SI-1)',
                    'Authorized for release to Australia (REL AUSTRALIA)',
                    'Authorized for release to Canada (REL CANADA)',
                    'This information has been authorized for release to CENTO (REL CENTO)',
                    'Authorized for release to Chile (REL CHILE)',
                    'Authorized for release to Denmark (REL DENMARK)',
                    'Authorized for release to Federal Republic of Germany (FEDERAL REPUBLIC OF GERMANY)',
                    'Authorized for release to France (REL FRANCE)',
                    'Authorized for release to Greece (REL GREECE)',
                    'Authorized for release to Israel (REL ISRAEL)',
                    'Authorized for release to Italy (REL ITALY)',
                    'Authorized for release to Japan (REL JAPAN)',
                    'Authorized for release to Jordan (REL JORDAN)',
                    'Authorized for release to NATO (REL NATO)',
                    'Authorized for release to NATO Forces (REL NATO FORCES)',
                    'Authorized for release to New Zealand (REL NEW ZEALAND)',
                    'Authorized for release to Norway (REL NORWAY)',
                    'Authorized for release to Taiwan (REL TAIWAN)',
                    'Authorized for release to Republic of Korea (REL REPUBLIC OF KOREA)',
                    'This Information has been Authorized for release to SEATO (REL SEATO)',
                    'Authorized for release to Denmark',
                    'Authorized for release to Spain (REL SPAIN)',
                    'Authorized for release to Sweden (REL SWEDEN)',
                    'Authorized for release to Thailand (REL THAILAND)',
                    'Authorized for release to Turkey (REL TURKEY)',
                    'Authorized for release to United Kingdom (REL UNITED KINGDOM)',
                    'Warning Notice - Intelligence sources or Methods Involved (WNINTEL)',
                  ],
                },
              ],
              req: false,
            },
            country_code: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'country_code',
              docs: 'Specify the country code of the CADRG files.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized:
                    "'None' | 'Abu Musa (Disputed Island In Persian Gulf)' | 'Afghanistan' | 'Albania' | 'Algeria' | 'American Samoa (US)' | 'Andaman Islands (IN)' | 'Andorra' | 'Angola' | 'Anquilla (Leeward Islands) (UK)' | 'Annobon (Pagulu) (EK)' | 'Antarctica' | 'Antigua-Barbuda' | 'Argentina' | 'Armenia' | 'Aruba (NL)' | 'Ashmore & Cartier Islands (AS)' | 'Australia' | 'Austria' | 'Azerbaijan' | 'Azores (PO)' | 'Bahama Islands' | 'Bahrain' | 'Baker Islands (SP)' | 'Bangladesh' | 'Barbados' | 'Bassas Da India (FR)' | 'Belarus' | 'Belgium' | 'Belize' | 'Benin' | 'Bermuda' | 'Bhutan' | 'Bolivia' | 'Bosnia-Herzegovina' | 'Botswana' | 'Bovet Island (NO)' | 'Brazil' | 'British Indian Ocean Territory (Chagos Archipelago)' | 'British Virgin Islands (Leeward Islands)' | 'Brunei' | 'Bulgaria' | 'Burkina Faso (Upper Volta)' | 'Myanmar (Burma)' | 'Burundi' | 'Cabinda (AO)' | 'Kampuchea (Cambodia)' | 'Cameroon' | 'Canada' | 'Canary Islands (SP)' | 'Cape Verde Islands' | 'Caroline Islands' | 'Cayman Islands' | 'Central African Republic' | 'Chad' | 'Chile' | 'China, People's Republic of' | 'Christmas Island (Indian Ocean) (AS)' | 'Clipperton Island (FR)' | 'Cocos Islands (Keeling) (AS)' | 'Columbia' | 'Comoro Islands (AS)' | 'Congo' | 'Cook Islands (NZ)' | 'Coral Sea Islands (AS)' | 'Costa Rica' | 'Cote d?Ivoire (Ivory Coast)' | 'Crete (Kriti) (GR)' | 'Croatia' | 'Cuba' | 'Cyprus' | 'Czech Republic' | 'Denmark' | 'Diego Garcia' | 'Djibouti' | 'Dominica' | 'Dominican Republic' | 'Easter Island (Isla De Pascua) (CI)' | 'Equador' | 'Egypt' | 'El Salvador' | 'Elobey, Islas De' | 'Equatorial Guinea' | 'Eritrea' | 'Estonia' | 'Ethiopia' | 'Europa Island (FR)' | 'Farroe Islands (DE)' | 'Falkland Islands (UK) (Malvinas)' | 'Fiji Islands' | 'Finland' | 'France' | 'French Guiana' | 'French Polynesia' | 'French Southern & Antarctic Lands' | 'Gabon' | 'Gambia' | 'Gaza Strip (Is)' | 'Georgia' | 'Germany' | 'Ghana' | 'Gibraltar (UK)' | 'Glorioso Island (Ma)' | 'Greece' | 'Greenland' | 'Grenada' | 'Guadeloupe (Leeward Islands)' | 'Guam' | 'Guatemala' | 'Guernsey (UK)' | 'Guinea' | 'Guinea-Bissau' | 'Guyana' | 'Haiti' | 'Heard Island & McDonald Is (AS)' | 'Honduras' | 'Hong Kong (UK)' | 'Howland Island (US)' | 'Hungary' | 'Iceland' | 'India' | 'Indonesia' | 'Iran' | 'Iraq' | 'Ireland' | 'Israel' | 'Italy' | 'Jamaica' | 'Jan Mayen Is (NO)' | 'Japan' | 'Jarvis Island (US)' | 'Jersey (UK)' | 'Johnston Atoll (US)' | 'Jordan' | 'Juan De Nova Islands (FR)' | 'Juan Fernandez' | 'Kazakhstan' | 'Kenya' | 'Kingman Reef (US)' | 'Korea, North' | 'Korea, South' | 'Kuwait' | 'Kirghizia' | 'Lakshadweep Islands (IN)' | 'Laos' | 'Latvia' | 'Lebanon' | 'Lesotho' | 'Liberia' | 'Libya' | 'Liechtenstein' | 'Lithuania' | 'Luxembourg' | 'Macao (PO)' | 'Macedonia' | 'Macais Nguema Biyogo' | 'Madagascar' | 'Madeira Islands (PO)' | 'Malawi' | 'Malaysia' | 'Maldives' | 'Mali' | 'Malta' | 'Isle of Man (UK)' | 'Republic of the Marshall Islands' | 'Martinique (FR)' | 'Mauritania' | 'Mauritius' | 'Mayotte (FR)' | 'Mexico' | 'Federated States of Micronesia' | 'Midway Island (US)' | 'Moldova' | 'Monaco' | 'Mongolia' | 'Montenegro' | 'Montserrat' | 'Morocco' | 'Mozambique' | 'Namibia' | 'Nauru' | 'Navassa Island (US)' | 'Nepal' | 'Netherlands' | 'Netherlands Antilles' | 'New Caledonia (FR)' | 'New Zealand' | 'Nicaragua' | 'Nicobar Islands (IN)' | 'Niger' | 'Nigeria' | 'Niue (NZ)' | 'Norfolk Islands (AS)' | 'Northern Ireland' | 'Northern Mariana Islands (US)' | 'Norway' | 'Okinawa (JA)' | 'Oman' | 'Pakistan' | 'Palau, Republic of (US)' | 'Palmyra Atoll (US)' | 'Panama' | 'Papua New Guinea' | 'Paracel Islands (CH)' | 'Paraguay' | 'Pemba Island (TZ)' | 'Peru' | 'Philippines' | 'Pitcairn Island (UK)' | 'Poland' | 'Portugal' | 'Puerto Rico (US)' | 'Qatar' | 'Reunion (FR)' | 'Romania' | 'Russia' | 'Rwanda' | 'Saint Helena' | 'Saint Lucia' | 'Saint Vincent and the Grenadines' | 'Sala Y Gomez (CI)' | 'San Ambrosia Island (CI)' | 'San Felix Island (CI)' | 'San Marino' | 'Sao Tome and Principe' | 'Sardinia (IT)' | 'Saudi Arabia' | 'Senegal' | 'Serbia' | 'Seychelles' | 'Sierra Leone' | 'Singapore' | 'Slovakia' | 'Slovenia' | 'Socotra (YM)' | 'Solomon Islands' | 'Somalia' | 'Republic of South Africa' | 'South Georgia & South Sandwich Is (UK)' | 'South Orkney Islands (UK)' | 'South Shetland Islands (UK)' | 'Spain' | 'Spratly Islands  (CH, RP, MY, VM)' | 'Sri Lanka' | 'St. Christopher-Nevis' | 'St. Pierre Miqurlon (CA)' | 'Sudan' | 'Surinam' | 'Svalbard (NO)' | 'Swaziland' | 'Sweden' | 'Switzerland' | 'Syria' | 'Taiwan and Penghu' | 'Tajikistan' | 'Tanzania' | 'Thailand' | 'Togo' | 'Tokelau (NZ)' | 'Tonga Islands' | 'Trinidad and Tobago' | 'Tromelin Island (FR)' | 'Tunisia' | 'Turkey' | 'Turkmenistan' | 'Turks and Caicos Islands (UK)' | 'Tuvalu' | 'Uganda' | 'Ukraine' | 'United Arab Emirates' | 'United Kingdom' | 'United States' | 'US miscellaneous Pacific Islands' | 'Uruguay' | 'Uzbekistan' | 'Vanuatu (Former New Hebrides)' | 'Vatican City' | 'Venezuela' | 'Vietnam' | 'Virgin Islands (US, UK)' | 'Wake Island (US)' | 'Wallis and Futuna Islands (FR)' | 'Walvis Bay (SF)' | 'West Bank' | 'Western Sahara (MO)' | 'Western Samoa' | 'Yemen' | 'Zaire' | 'Zambia' | 'Zanzibar (TZ)' | 'Zimbabwe'",
                  args: [],
                  meta: { default: 'None' },
                  value: [
                    'None',
                    'Abu Musa (Disputed Island In Persian Gulf)',
                    'Afghanistan',
                    'Albania',
                    'Algeria',
                    'American Samoa (US)',
                    'Andaman Islands (IN)',
                    'Andorra',
                    'Angola',
                    'Anquilla (Leeward Islands) (UK)',
                    'Annobon (Pagulu) (EK)',
                    'Antarctica',
                    'Antigua-Barbuda',
                    'Argentina',
                    'Armenia',
                    'Aruba (NL)',
                    'Ashmore & Cartier Islands (AS)',
                    'Australia',
                    'Austria',
                    'Azerbaijan',
                    'Azores (PO)',
                    'Bahama Islands',
                    'Bahrain',
                    'Baker Islands (SP)',
                    'Bangladesh',
                    'Barbados',
                    'Bassas Da India (FR)',
                    'Belarus',
                    'Belgium',
                    'Belize',
                    'Benin',
                    'Bermuda',
                    'Bhutan',
                    'Bolivia',
                    'Bosnia-Herzegovina',
                    'Botswana',
                    'Bovet Island (NO)',
                    'Brazil',
                    'British Indian Ocean Territory (Chagos Archipelago)',
                    'British Virgin Islands (Leeward Islands)',
                    'Brunei',
                    'Bulgaria',
                    'Burkina Faso (Upper Volta)',
                    'Myanmar (Burma)',
                    'Burundi',
                    'Cabinda (AO)',
                    'Kampuchea (Cambodia)',
                    'Cameroon',
                    'Canada',
                    'Canary Islands (SP)',
                    'Cape Verde Islands',
                    'Caroline Islands',
                    'Cayman Islands',
                    'Central African Republic',
                    'Chad',
                    'Chile',
                    "China, People's Republic of",
                    'Christmas Island (Indian Ocean) (AS)',
                    'Clipperton Island (FR)',
                    'Cocos Islands (Keeling) (AS)',
                    'Columbia',
                    'Comoro Islands (AS)',
                    'Congo',
                    'Cook Islands (NZ)',
                    'Coral Sea Islands (AS)',
                    'Costa Rica',
                    'Cote d?Ivoire (Ivory Coast)',
                    'Crete (Kriti) (GR)',
                    'Croatia',
                    'Cuba',
                    'Cyprus',
                    'Czech Republic',
                    'Denmark',
                    'Diego Garcia',
                    'Djibouti',
                    'Dominica',
                    'Dominican Republic',
                    'Easter Island (Isla De Pascua) (CI)',
                    'Equador',
                    'Egypt',
                    'El Salvador',
                    'Elobey, Islas De',
                    'Equatorial Guinea',
                    'Eritrea',
                    'Estonia',
                    'Ethiopia',
                    'Europa Island (FR)',
                    'Farroe Islands (DE)',
                    'Falkland Islands (UK) (Malvinas)',
                    'Fiji Islands',
                    'Finland',
                    'France',
                    'French Guiana',
                    'French Polynesia',
                    'French Southern & Antarctic Lands',
                    'Gabon',
                    'Gambia',
                    'Gaza Strip (Is)',
                    'Georgia',
                    'Germany',
                    'Ghana',
                    'Gibraltar (UK)',
                    'Glorioso Island (Ma)',
                    'Greece',
                    'Greenland',
                    'Grenada',
                    'Guadeloupe (Leeward Islands)',
                    'Guam',
                    'Guatemala',
                    'Guernsey (UK)',
                    'Guinea',
                    'Guinea-Bissau',
                    'Guyana',
                    'Haiti',
                    'Heard Island & McDonald Is (AS)',
                    'Honduras',
                    'Hong Kong (UK)',
                    'Howland Island (US)',
                    'Hungary',
                    'Iceland',
                    'India',
                    'Indonesia',
                    'Iran',
                    'Iraq',
                    'Ireland',
                    'Israel',
                    'Italy',
                    'Jamaica',
                    'Jan Mayen Is (NO)',
                    'Japan',
                    'Jarvis Island (US)',
                    'Jersey (UK)',
                    'Johnston Atoll (US)',
                    'Jordan',
                    'Juan De Nova Islands (FR)',
                    'Juan Fernandez',
                    'Kazakhstan',
                    'Kenya',
                    'Kingman Reef (US)',
                    'Korea, North',
                    'Korea, South',
                    'Kuwait',
                    'Kirghizia',
                    'Lakshadweep Islands (IN)',
                    'Laos',
                    'Latvia',
                    'Lebanon',
                    'Lesotho',
                    'Liberia',
                    'Libya',
                    'Liechtenstein',
                    'Lithuania',
                    'Luxembourg',
                    'Macao (PO)',
                    'Macedonia',
                    'Macais Nguema Biyogo',
                    'Madagascar',
                    'Madeira Islands (PO)',
                    'Malawi',
                    'Malaysia',
                    'Maldives',
                    'Mali',
                    'Malta',
                    'Isle of Man (UK)',
                    'Republic of the Marshall Islands',
                    'Martinique (FR)',
                    'Mauritania',
                    'Mauritius',
                    'Mayotte (FR)',
                    'Mexico',
                    'Federated States of Micronesia',
                    'Midway Island (US)',
                    'Moldova',
                    'Monaco',
                    'Mongolia',
                    'Montenegro',
                    'Montserrat',
                    'Morocco',
                    'Mozambique',
                    'Namibia',
                    'Nauru',
                    'Navassa Island (US)',
                    'Nepal',
                    'Netherlands',
                    'Netherlands Antilles',
                    'New Caledonia (FR)',
                    'New Zealand',
                    'Nicaragua',
                    'Nicobar Islands (IN)',
                    'Niger',
                    'Nigeria',
                    'Niue (NZ)',
                    'Norfolk Islands (AS)',
                    'Northern Ireland',
                    'Northern Mariana Islands (US)',
                    'Norway',
                    'Okinawa (JA)',
                    'Oman',
                    'Pakistan',
                    'Palau, Republic of (US)',
                    'Palmyra Atoll (US)',
                    'Panama',
                    'Papua New Guinea',
                    'Paracel Islands (CH)',
                    'Paraguay',
                    'Pemba Island (TZ)',
                    'Peru',
                    'Philippines',
                    'Pitcairn Island (UK)',
                    'Poland',
                    'Portugal',
                    'Puerto Rico (US)',
                    'Qatar',
                    'Reunion (FR)',
                    'Romania',
                    'Russia',
                    'Rwanda',
                    'Saint Helena',
                    'Saint Lucia',
                    'Saint Vincent and the Grenadines',
                    'Sala Y Gomez (CI)',
                    'San Ambrosia Island (CI)',
                    'San Felix Island (CI)',
                    'San Marino',
                    'Sao Tome and Principe',
                    'Sardinia (IT)',
                    'Saudi Arabia',
                    'Senegal',
                    'Serbia',
                    'Seychelles',
                    'Sierra Leone',
                    'Singapore',
                    'Slovakia',
                    'Slovenia',
                    'Socotra (YM)',
                    'Solomon Islands',
                    'Somalia',
                    'Republic of South Africa',
                    'South Georgia & South Sandwich Is (UK)',
                    'South Orkney Islands (UK)',
                    'South Shetland Islands (UK)',
                    'Spain',
                    'Spratly Islands  (CH, RP, MY, VM)',
                    'Sri Lanka',
                    'St. Christopher-Nevis',
                    'St. Pierre Miqurlon (CA)',
                    'Sudan',
                    'Surinam',
                    'Svalbard (NO)',
                    'Swaziland',
                    'Sweden',
                    'Switzerland',
                    'Syria',
                    'Taiwan and Penghu',
                    'Tajikistan',
                    'Tanzania',
                    'Thailand',
                    'Togo',
                    'Tokelau (NZ)',
                    'Tonga Islands',
                    'Trinidad and Tobago',
                    'Tromelin Island (FR)',
                    'Tunisia',
                    'Turkey',
                    'Turkmenistan',
                    'Turks and Caicos Islands (UK)',
                    'Tuvalu',
                    'Uganda',
                    'Ukraine',
                    'United Arab Emirates',
                    'United Kingdom',
                    'United States',
                    'US miscellaneous Pacific Islands',
                    'Uruguay',
                    'Uzbekistan',
                    'Vanuatu (Former New Hebrides)',
                    'Vatican City',
                    'Venezuela',
                    'Vietnam',
                    'Virgin Islands (US, UK)',
                    'Wake Island (US)',
                    'Wallis and Futuna Islands (FR)',
                    'Walvis Bay (SF)',
                    'West Bank',
                    'Western Sahara (MO)',
                    'Western Samoa',
                    'Yemen',
                    'Zaire',
                    'Zambia',
                    'Zanzibar (TZ)',
                    'Zimbabwe',
                  ],
                },
              ],
              req: false,
            },
            originating_station_id: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'originating_station_id',
              docs: 'Specify the Originating Station ID tag used by NITF.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized: 'String',
                  args: [],
                  meta: { default: '' },
                },
              ],
              req: false,
            },
            originator_name: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'originator_name',
              docs: "Specify the Originator's Name tag used by NITF.",
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized: 'String',
                  args: [],
                  meta: { default: '' },
                },
              ],
              req: false,
            },
            output_directory: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'in',
              private: false,
              display: 'output_directory',
              docs: 'Directory in which the resulting CADRG files will be written.',
              type: [
                {
                  name: 'String',
                  display: 'String',
                  serialized: 'String',
                  args: [],
                  meta: { isFolder: true, isUri: true },
                },
              ],
              req: true,
            },
            output_raster: {
              source: 'user',
              code: true,
              pos: [0, 0, 0],
              direction: 'out',
              private: false,
              display: 'output_raster',
              docs: 'This is an array of one or more rasters produced by the export.',
              type: [
                {
                  name: 'Array',
                  display: 'Array<ENVIRASTER>',
                  serialized: 'Array<ENVIRASTER>',
                  args: [
                    [
                      {
                        name: 'ENVIRASTER',
                        display: 'ENVIRASTER',
                        serialized: 'ENVIRASTER',
                        args: [],
                        meta: {},
                      },
                    ],
                  ],
                  meta: { dimensions: ['*'] },
                },
              ],
              req: true,
            },
          },
        },
      },
    };

    // verify results
    expect(expected).toEqual(TaskToGlobalToken(task));
  });
});
