import { TextMateParse } from '@idl/tests/helpers';

describe(`[auto generated] Validates case statement`, () => {
  it(`[auto generated] parses case loop with many syntaxes`, async () => {
    // test code to extract tokens from
    const code = [
      `CASE x OF`,
      `   ; something cool`,
      `1 $`,
      `  : $`,
      `   PRINT, 'one' + func()`,
      `ELSE: BEGIN`,
      `   dat = {myStruct}`,
      `   PRINT, 'Please enter a value between 1 and 4'`,
      `   END`,
      `ENDCASE`,
    ];

    // extract tokens
    const tokenized = await TextMateParse(code);

    // define expected tokens
    const expected = [
      {
        line: 0,
        match: 'CASE',
        startIndex: 0,
        endIndex: 4,
        scopes: ['source.idl', 'group.logic.case.idl', 'keyword.control.idl'],
      },
      {
        line: 0,
        match: 'x',
        startIndex: 5,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'variable.other.readwrite.ts.idl',
        ],
      },
      {
        line: 0,
        match: 'OF',
        startIndex: 7,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 1,
        match: '; ',
        startIndex: 3,
        endIndex: 5,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'comment.line.idl',
        ],
      },
      {
        line: 1,
        match: 'something cool',
        startIndex: 5,
        endIndex: 19,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'comment.line.idl',
        ],
      },
      {
        line: 2,
        match: '1',
        startIndex: 0,
        endIndex: 1,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'constant.numeric.idl',
        ],
      },
      {
        line: 2,
        match: '$',
        startIndex: 2,
        endIndex: 3,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.line-continuation.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 3,
        match: ':',
        startIndex: 2,
        endIndex: 3,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 3,
        match: '$',
        startIndex: 4,
        endIndex: 5,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.line-continuation.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 4,
        match: 'PRINT',
        startIndex: 3,
        endIndex: 8,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'support.function.idl-procedure',
        ],
      },
      {
        line: 4,
        match: ',',
        startIndex: 8,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 4,
        match: "'",
        startIndex: 10,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 4,
        match: 'one',
        startIndex: 11,
        endIndex: 14,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 4,
        match: "'",
        startIndex: 14,
        endIndex: 15,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 4,
        match: '+',
        startIndex: 16,
        endIndex: 17,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 4,
        match: 'func',
        startIndex: 18,
        endIndex: 22,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'group.call.func.idl',
          'entity.name.function.idl',
        ],
      },
      {
        line: 4,
        match: '(',
        startIndex: 22,
        endIndex: 23,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'group.call.func.idl',
          'meta.brace.round.idl',
        ],
      },
      {
        line: 4,
        match: ')',
        startIndex: 23,
        endIndex: 24,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'group.call.func.idl',
          'meta.brace.round.idl',
        ],
      },
      {
        line: 5,
        match: 'ELSE:',
        startIndex: 0,
        endIndex: 5,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 5,
        match: ' BEGIN',
        startIndex: 5,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 6,
        match: 'dat',
        startIndex: 3,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'variable.other.readwrite.ts.idl',
        ],
      },
      {
        line: 6,
        match: '=',
        startIndex: 7,
        endIndex: 8,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.assignment.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 6,
        match: '{',
        startIndex: 9,
        endIndex: 10,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.assignment.idl',
          'group.structure.idl',
          'meta.brace.idl',
        ],
      },
      {
        line: 6,
        match: 'myStruct',
        startIndex: 10,
        endIndex: 18,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.assignment.idl',
          'group.structure.idl',
          'entity.name.type.idl',
        ],
      },
      {
        line: 6,
        match: '}',
        startIndex: 18,
        endIndex: 19,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.assignment.idl',
          'group.structure.idl',
          'meta.brace.idl',
        ],
      },
      {
        line: 7,
        match: 'PRINT',
        startIndex: 3,
        endIndex: 8,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.call.pro.idl',
          'support.function.idl-procedure',
        ],
      },
      {
        line: 7,
        match: ',',
        startIndex: 8,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.call.pro.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 7,
        match: "'",
        startIndex: 10,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 7,
        match: 'Please enter a value between 1 and 4',
        startIndex: 11,
        endIndex: 47,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 7,
        match: "'",
        startIndex: 47,
        endIndex: 48,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 8,
        match: '   END',
        startIndex: 0,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 9,
        match: 'ENDCASE',
        startIndex: 0,
        endIndex: 7,
        scopes: ['source.idl', 'group.logic.case.idl', 'keyword.control.idl'],
      },
    ];
    expect(expected).toEqual(tokenized);
  });

  it(`[auto generated] nested case statement`, async () => {
    // test code to extract tokens from
    const code = [
      `CASE x OF`,
      `1: PRINT, 'one'`,
      `ELSE: BEGIN`,
      `  CASE x OF`,
      `    2: PRINT, 'two'`,
      `    ELSE: BEGIN`,
      `    END`,
      `  ENDCASE`,
      `END`,
      `ENDCASE`,
    ];

    // extract tokens
    const tokenized = await TextMateParse(code);

    // define expected tokens
    const expected = [
      {
        line: 0,
        match: 'CASE',
        startIndex: 0,
        endIndex: 4,
        scopes: ['source.idl', 'group.logic.case.idl', 'keyword.control.idl'],
      },
      {
        line: 0,
        match: 'x',
        startIndex: 5,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'variable.other.readwrite.ts.idl',
        ],
      },
      {
        line: 0,
        match: 'OF',
        startIndex: 7,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 1,
        match: '1',
        startIndex: 0,
        endIndex: 1,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'constant.numeric.idl',
        ],
      },
      {
        line: 1,
        match: ':',
        startIndex: 1,
        endIndex: 2,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 1,
        match: 'PRINT',
        startIndex: 3,
        endIndex: 8,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'support.function.idl-procedure',
        ],
      },
      {
        line: 1,
        match: ',',
        startIndex: 8,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 1,
        match: "'",
        startIndex: 10,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 1,
        match: 'one',
        startIndex: 11,
        endIndex: 14,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 1,
        match: "'",
        startIndex: 14,
        endIndex: 15,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 2,
        match: 'ELSE:',
        startIndex: 0,
        endIndex: 5,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 2,
        match: ' BEGIN',
        startIndex: 5,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 3,
        match: '  CASE',
        startIndex: 0,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 3,
        match: 'x',
        startIndex: 7,
        endIndex: 8,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'variable.other.readwrite.ts.idl',
        ],
      },
      {
        line: 3,
        match: 'OF',
        startIndex: 9,
        endIndex: 11,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 4,
        match: '2',
        startIndex: 4,
        endIndex: 5,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'constant.numeric.idl',
        ],
      },
      {
        line: 4,
        match: ':',
        startIndex: 5,
        endIndex: 6,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 4,
        match: 'PRINT',
        startIndex: 7,
        endIndex: 12,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'support.function.idl-procedure',
        ],
      },
      {
        line: 4,
        match: ',',
        startIndex: 12,
        endIndex: 13,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'keyword.operator.idl',
        ],
      },
      {
        line: 4,
        match: "'",
        startIndex: 14,
        endIndex: 15,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 4,
        match: 'two',
        startIndex: 15,
        endIndex: 18,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 4,
        match: "'",
        startIndex: 18,
        endIndex: 19,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.call.pro.idl',
          'string.quoted.single.idl',
        ],
      },
      {
        line: 5,
        match: '    ELSE:',
        startIndex: 0,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 5,
        match: ' BEGIN',
        startIndex: 9,
        endIndex: 15,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 6,
        match: '    END',
        startIndex: 0,
        endIndex: 7,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 7,
        match: 'ENDCASE',
        startIndex: 2,
        endIndex: 9,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'group.logic.case.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 8,
        match: 'END',
        startIndex: 0,
        endIndex: 3,
        scopes: [
          'source.idl',
          'group.logic.case.idl',
          'group.logic.of.idl',
          'group.logic.then.idl',
          'group.block.idl',
          'keyword.control.idl',
        ],
      },
      {
        line: 9,
        match: 'ENDCASE',
        startIndex: 0,
        endIndex: 7,
        scopes: ['source.idl', 'group.logic.case.idl', 'keyword.control.idl'],
      },
    ];
    expect(expected).toEqual(tokenized);
  });
});
