export * from './lib/apply-fixers';
export * from './lib/fixes-for/14.colon-in-func';
export * from './lib/fixes-for/15.colon-in-func-method';
export * from './lib/fixes-for/20.return-vals-pro';
export * from './lib/fixes-for/21.return-vals-func';
export * from './lib/fixes-for/31.return-missing';
export * from './lib/fixes-for/38.no-comp-opt';
export * from './lib/fixes-for/76.init-method-pro';
export * from './lib/fixes-for/105.illegal-var-index';
