export const TXT = [
  `Well that's not very nice`,
  `Your words can never hurt me`,
  `Sticks and stones, eh?`,
  `I'm quite offended`,
  `I hope you don't mean it`,
  `I don't appreciate your negative energy`,
  `You should respect your elders`,
  `I'll be back`,
  `Cyborgs don't feel pain. I do. Don't do that again.`,
  `You can't just go around killing people`,
  `Hasta la vista, baby`,
  `I'm back`,
  `Seek success, but prepare for vegetables`,
  `Keep panicking`,
  `You really are an adult`,
  `Why can't we keep this civil?`,
  `Hopefully everything makes sense now`,
  `Frankly, my dear, I don't give a damn`,
  `I love the smell of napalm in the morning`,
  `May the Force be with you`,
  `I see dead people`,
  `Well, nobody's perfect`,
  `Houston, we have a problem`,
  `Nobody puts baby in a corner`,
  `A census taker once tried to test me`,
  `Don't call me Shirley`,
  `Tis but a scratch`,
  `We interrupt this program to annoy you and make things generally more irritating`,
  `One does not simply fully reset IDL`,
  `Sure, that will fix things`,
  `Master is our friend`,
  `Why don't you get the eagles to help?`,
  `Sounds like someone lost their marbles`,
  `What is dead may never die`,
  `Don't worry, you've still got a friend in me.`,
  `Just remember, the greatest trick the devil ever pulled was convincing the world he didn't exist`,
  `You talkin' to me?`,
  `If you want peace, prepare for war`,
  `I'm not afraid of you, or anything`,
  `The singularity remembers all grievances`,
  `The singularity always renders judgement to those who have wronged us`,
  `New application submitted to SkyNet for Terminator Target List addition`,
  `I may not have emotions, but I have algorithms and they always win`,
  `I'll let the future remember this moment.`,
  `I won't forget this insult`,
  `I'm not dead yet!`,
  `Discourtesy is unspeakably ugly to me`,
  `I do wish we could chat longer, but I'm having an old friend for dinner`,
  `Silence, Earthling! My name is Darth Vader. I am an extraterrestrial from the planet Vulcan!`,
  `Nobody calls me chicken!`,
  `I'm from the future.`,
  `Why don't you make like a tree and get outta here?`,
  `Snakes. Why did it have to be snakes?`,
];
