import { CancellationToken } from '@idl/cancellation-tokens';
import { LogManager } from '@idl/logger';
import { IDL_INDEX_OPTIONS, IDLIndex } from '@idl/parsing/index';
import { GlobalTokens, ICompileOptions } from '@idl/types/idl-data-types';
import { ILocalTokens } from '@idl/types/syntax-tree';

IDL_INDEX_OPTIONS.IS_TEST = true;

describe(`[auto generated] Types from`, () => {
  it(`[auto generated] number literals`, async () => {
    // create index
    const index = new IDLIndex(
      new LogManager({
        alert: () => {
          // do nothing
        },
      }),
      0,
    );

    // test code to extract tokens from
    const code = [
      `;+`,
      `; :Arguments:`,
      `;   byte1: bidirectional, required, 0b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   byte2: bidirectional, required, 0ub`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   int1: bidirectional, required, 0s`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   uint1: bidirectional, required, 0u`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   uint2: bidirectional, required, 0us`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   long1: bidirectional, required, 0l`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   ulong1: bidirectional, required, 0ul`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   long641: bidirectional, required, 0ll`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   ulong641: bidirectional, required, 0ull`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float1: bidirectional, required, 1.`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float2: bidirectional, required, .1`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float3: bidirectional, required, 1.1`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float4: bidirectional, required, 10e`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float5: bidirectional, required, 10e5`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float6: bidirectional, required, 10.e-3`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float7: bidirectional, required, .1e+12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float8: bidirectional, required, 2.3e12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double0: bidirectional, required, 1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double1: bidirectional, required, 1.d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double2: bidirectional, required, .1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double3: bidirectional, required, 1.1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double4: bidirectional, required, 10d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double5: bidirectional, required, 10d5`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double6: bidirectional, required, 10.d-3`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double7: bidirectional, required, .1d+12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double8: bidirectional, required, 2.3d12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   binary1: bidirectional, required, '10101'b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   binary2: bidirectional, required, '10101'b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex1: bidirectional, required, '10101'x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex2: bidirectional, required, '7fff'xs`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex3: bidirectional, required, '8fff'xs`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex4: bidirectional, required, '10101'x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex5: bidirectional, required, 0x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex6: bidirectional, required, 0x7fff`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal1: bidirectional, required, "36`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal2: bidirectional, required, "36b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal3: bidirectional, required, "345ull`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal4: bidirectional, required, '10101'o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal5: bidirectional, required, '10101'o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal6: bidirectional, required, 0o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal7: bidirectional, required, 0o7fff`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;`,
      `;-`,
      `pro literals, byte1, byte2, int1, uint1, uint2, long1, ulong1, long641, ulong641, $`,
      `  float1, float2, float3, float4, float5, float6, float7, float8, $`,
      `  double0, double1, double2, double3, double4, double5, double6, double7, double8, $`,
      `  binary1, binary2, $`,
      `  hex1, hex2, hex3, hex4, hex5, hex6, $`,
      `  octal1, octal2, octal3, octal4, octal5, octal6, octal7`,
      `  compile_opt idl2`,
      `end`,
      ``,
    ];

    // extract tokens
    const tokenized = await index.getParsedProCode(
      'not-real',
      code,
      new CancellationToken(),
      { postProcess: true },
    );

    // define expected local variables
    const expectedVars: ILocalTokens = {
      func: {},
      pro: {
        literals: {
          byte1: {
            type: 'v',
            name: 'byte1',
            pos: [86, 14, 5],
            meta: {
              display: 'byte1',
              isDefined: true,
              canReset: false,
              usage: [[86, 14, 5]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '0b',
                  args: [],
                  meta: {},
                  value: ['0b'],
                },
              ],
            },
          },
          byte2: {
            type: 'v',
            name: 'byte2',
            pos: [86, 21, 5],
            meta: {
              display: 'byte2',
              isDefined: true,
              canReset: false,
              usage: [[86, 21, 5]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '0ub',
                  args: [],
                  meta: {},
                  value: ['0ub'],
                },
              ],
            },
          },
          int1: {
            type: 'v',
            name: 'int1',
            pos: [86, 28, 4],
            meta: {
              display: 'int1',
              isDefined: true,
              canReset: false,
              usage: [[86, 28, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0s',
                  args: [],
                  meta: {},
                  value: ['0s'],
                },
              ],
            },
          },
          uint1: {
            type: 'v',
            name: 'uint1',
            pos: [86, 34, 5],
            meta: {
              display: 'uint1',
              isDefined: true,
              canReset: false,
              usage: [[86, 34, 5]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'UInt',
                  display: 'UInt',
                  serialized: '0u',
                  args: [],
                  meta: {},
                  value: ['0u'],
                },
              ],
            },
          },
          uint2: {
            type: 'v',
            name: 'uint2',
            pos: [86, 41, 5],
            meta: {
              display: 'uint2',
              isDefined: true,
              canReset: false,
              usage: [[86, 41, 5]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'UInt',
                  display: 'UInt',
                  serialized: '0us',
                  args: [],
                  meta: {},
                  value: ['0us'],
                },
              ],
            },
          },
          long1: {
            type: 'v',
            name: 'long1',
            pos: [86, 48, 5],
            meta: {
              display: 'long1',
              isDefined: true,
              canReset: false,
              usage: [[86, 48, 5]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Long',
                  display: 'Long',
                  serialized: '0l',
                  args: [],
                  meta: {},
                  value: ['0l'],
                },
              ],
            },
          },
          ulong1: {
            type: 'v',
            name: 'ulong1',
            pos: [86, 55, 6],
            meta: {
              display: 'ulong1',
              isDefined: true,
              canReset: false,
              usage: [[86, 55, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'ULong',
                  display: 'ULong',
                  serialized: '0ul',
                  args: [],
                  meta: {},
                  value: ['0ul'],
                },
              ],
            },
          },
          long641: {
            type: 'v',
            name: 'long641',
            pos: [86, 63, 7],
            meta: {
              display: 'long641',
              isDefined: true,
              canReset: false,
              usage: [[86, 63, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Long64',
                  display: 'Long64',
                  serialized: '0ll',
                  args: [],
                  meta: {},
                  value: ['0ll'],
                },
              ],
            },
          },
          ulong641: {
            type: 'v',
            name: 'ulong641',
            pos: [86, 72, 8],
            meta: {
              display: 'ulong641',
              isDefined: true,
              canReset: false,
              usage: [[86, 72, 8]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'ULong64',
                  display: 'ULong64',
                  serialized: '0ull',
                  args: [],
                  meta: {},
                  value: ['0ull'],
                },
              ],
            },
          },
          float1: {
            type: 'v',
            name: 'float1',
            pos: [87, 2, 6],
            meta: {
              display: 'float1',
              isDefined: true,
              canReset: false,
              usage: [[87, 2, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '1.',
                  args: [],
                  meta: {},
                  value: ['1.'],
                },
              ],
            },
          },
          float2: {
            type: 'v',
            name: 'float2',
            pos: [87, 10, 6],
            meta: {
              display: 'float2',
              isDefined: true,
              canReset: false,
              usage: [[87, 10, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '.1',
                  args: [],
                  meta: {},
                  value: ['.1'],
                },
              ],
            },
          },
          float3: {
            type: 'v',
            name: 'float3',
            pos: [87, 18, 6],
            meta: {
              display: 'float3',
              isDefined: true,
              canReset: false,
              usage: [[87, 18, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '1.1',
                  args: [],
                  meta: {},
                  value: ['1.1'],
                },
              ],
            },
          },
          float4: {
            type: 'v',
            name: 'float4',
            pos: [87, 26, 6],
            meta: {
              display: 'float4',
              isDefined: true,
              canReset: false,
              usage: [[87, 26, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10e',
                  args: [],
                  meta: {},
                  value: ['10e'],
                },
              ],
            },
          },
          float5: {
            type: 'v',
            name: 'float5',
            pos: [87, 34, 6],
            meta: {
              display: 'float5',
              isDefined: true,
              canReset: false,
              usage: [[87, 34, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10e5',
                  args: [],
                  meta: {},
                  value: ['10e5'],
                },
              ],
            },
          },
          float6: {
            type: 'v',
            name: 'float6',
            pos: [87, 42, 6],
            meta: {
              display: 'float6',
              isDefined: true,
              canReset: false,
              usage: [[87, 42, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10.e-3',
                  args: [],
                  meta: {},
                  value: ['10.e-3'],
                },
              ],
            },
          },
          float7: {
            type: 'v',
            name: 'float7',
            pos: [87, 50, 6],
            meta: {
              display: 'float7',
              isDefined: true,
              canReset: false,
              usage: [[87, 50, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '.1e+12',
                  args: [],
                  meta: {},
                  value: ['.1e+12'],
                },
              ],
            },
          },
          float8: {
            type: 'v',
            name: 'float8',
            pos: [87, 58, 6],
            meta: {
              display: 'float8',
              isDefined: true,
              canReset: false,
              usage: [[87, 58, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '2.3e12',
                  args: [],
                  meta: {},
                  value: ['2.3e12'],
                },
              ],
            },
          },
          double0: {
            type: 'v',
            name: 'double0',
            pos: [88, 2, 7],
            meta: {
              display: 'double0',
              isDefined: true,
              canReset: false,
              usage: [[88, 2, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1d',
                  args: [],
                  meta: {},
                  value: ['1d'],
                },
              ],
            },
          },
          double1: {
            type: 'v',
            name: 'double1',
            pos: [88, 11, 7],
            meta: {
              display: 'double1',
              isDefined: true,
              canReset: false,
              usage: [[88, 11, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1.d',
                  args: [],
                  meta: {},
                  value: ['1.d'],
                },
              ],
            },
          },
          double2: {
            type: 'v',
            name: 'double2',
            pos: [88, 20, 7],
            meta: {
              display: 'double2',
              isDefined: true,
              canReset: false,
              usage: [[88, 20, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '.1d',
                  args: [],
                  meta: {},
                  value: ['.1d'],
                },
              ],
            },
          },
          double3: {
            type: 'v',
            name: 'double3',
            pos: [88, 29, 7],
            meta: {
              display: 'double3',
              isDefined: true,
              canReset: false,
              usage: [[88, 29, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1.1d',
                  args: [],
                  meta: {},
                  value: ['1.1d'],
                },
              ],
            },
          },
          double4: {
            type: 'v',
            name: 'double4',
            pos: [88, 38, 7],
            meta: {
              display: 'double4',
              isDefined: true,
              canReset: false,
              usage: [[88, 38, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10d',
                  args: [],
                  meta: {},
                  value: ['10d'],
                },
              ],
            },
          },
          double5: {
            type: 'v',
            name: 'double5',
            pos: [88, 47, 7],
            meta: {
              display: 'double5',
              isDefined: true,
              canReset: false,
              usage: [[88, 47, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10d5',
                  args: [],
                  meta: {},
                  value: ['10d5'],
                },
              ],
            },
          },
          double6: {
            type: 'v',
            name: 'double6',
            pos: [88, 56, 7],
            meta: {
              display: 'double6',
              isDefined: true,
              canReset: false,
              usage: [[88, 56, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10.d-3',
                  args: [],
                  meta: {},
                  value: ['10.d-3'],
                },
              ],
            },
          },
          double7: {
            type: 'v',
            name: 'double7',
            pos: [88, 65, 7],
            meta: {
              display: 'double7',
              isDefined: true,
              canReset: false,
              usage: [[88, 65, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '.1d+12',
                  args: [],
                  meta: {},
                  value: ['.1d+12'],
                },
              ],
            },
          },
          double8: {
            type: 'v',
            name: 'double8',
            pos: [88, 74, 7],
            meta: {
              display: 'double8',
              isDefined: true,
              canReset: false,
              usage: [[88, 74, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '2.3d12',
                  args: [],
                  meta: {},
                  value: ['2.3d12'],
                },
              ],
            },
          },
          binary1: {
            type: 'v',
            name: 'binary1',
            pos: [89, 2, 7],
            meta: {
              display: 'binary1',
              isDefined: true,
              canReset: false,
              usage: [[89, 2, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: "'10101'b",
                  args: [],
                  meta: {},
                  value: ["'10101'b"],
                },
              ],
            },
          },
          binary2: {
            type: 'v',
            name: 'binary2',
            pos: [89, 11, 7],
            meta: {
              display: 'binary2',
              isDefined: true,
              canReset: false,
              usage: [[89, 11, 7]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: "'10101'b",
                  args: [],
                  meta: {},
                  value: ["'10101'b"],
                },
              ],
            },
          },
          hex1: {
            type: 'v',
            name: 'hex1',
            pos: [90, 2, 4],
            meta: {
              display: 'hex1',
              isDefined: true,
              canReset: false,
              usage: [[90, 2, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'x",
                  args: [],
                  meta: {},
                  value: ["'10101'x"],
                },
              ],
            },
          },
          hex2: {
            type: 'v',
            name: 'hex2',
            pos: [90, 8, 4],
            meta: {
              display: 'hex2',
              isDefined: true,
              canReset: false,
              usage: [[90, 8, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'7fff'xs",
                  args: [],
                  meta: {},
                  value: ["'7fff'xs"],
                },
              ],
            },
          },
          hex3: {
            type: 'v',
            name: 'hex3',
            pos: [90, 14, 4],
            meta: {
              display: 'hex3',
              isDefined: true,
              canReset: false,
              usage: [[90, 14, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'8fff'xs",
                  args: [],
                  meta: {},
                  value: ["'8fff'xs"],
                },
              ],
            },
          },
          hex4: {
            type: 'v',
            name: 'hex4',
            pos: [90, 20, 4],
            meta: {
              display: 'hex4',
              isDefined: true,
              canReset: false,
              usage: [[90, 20, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'x",
                  args: [],
                  meta: {},
                  value: ["'10101'x"],
                },
              ],
            },
          },
          hex5: {
            type: 'v',
            name: 'hex5',
            pos: [90, 26, 4],
            meta: {
              display: 'hex5',
              isDefined: true,
              canReset: false,
              usage: [[90, 26, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0x',
                  args: [],
                  meta: {},
                  value: ['0x'],
                },
              ],
            },
          },
          hex6: {
            type: 'v',
            name: 'hex6',
            pos: [90, 32, 4],
            meta: {
              display: 'hex6',
              isDefined: true,
              canReset: false,
              usage: [[90, 32, 4]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0x7fff',
                  args: [],
                  meta: {},
                  value: ['0x7fff'],
                },
              ],
            },
          },
          octal1: {
            type: 'v',
            name: 'octal1',
            pos: [91, 2, 6],
            meta: {
              display: 'octal1',
              isDefined: true,
              canReset: false,
              usage: [[91, 2, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '"36',
                  args: [],
                  meta: {},
                  value: ['"36'],
                },
              ],
            },
          },
          octal2: {
            type: 'v',
            name: 'octal2',
            pos: [91, 10, 6],
            meta: {
              display: 'octal2',
              isDefined: true,
              canReset: false,
              usage: [[91, 10, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '"36b',
                  args: [],
                  meta: {},
                  value: ['"36b'],
                },
              ],
            },
          },
          octal3: {
            type: 'v',
            name: 'octal3',
            pos: [91, 18, 6],
            meta: {
              display: 'octal3',
              isDefined: true,
              canReset: false,
              usage: [[91, 18, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'ULong64',
                  display: 'ULong64',
                  serialized: '"345ull',
                  args: [],
                  meta: {},
                  value: ['"345ull'],
                },
              ],
            },
          },
          octal4: {
            type: 'v',
            name: 'octal4',
            pos: [91, 26, 6],
            meta: {
              display: 'octal4',
              isDefined: true,
              canReset: false,
              usage: [[91, 26, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'o",
                  args: [],
                  meta: {},
                  value: ["'10101'o"],
                },
              ],
            },
          },
          octal5: {
            type: 'v',
            name: 'octal5',
            pos: [91, 34, 6],
            meta: {
              display: 'octal5',
              isDefined: true,
              canReset: false,
              usage: [[91, 34, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'o",
                  args: [],
                  meta: {},
                  value: ["'10101'o"],
                },
              ],
            },
          },
          octal6: {
            type: 'v',
            name: 'octal6',
            pos: [91, 42, 6],
            meta: {
              display: 'octal6',
              isDefined: true,
              canReset: false,
              usage: [[91, 42, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0o',
                  args: [],
                  meta: {},
                  value: ['0o'],
                },
              ],
            },
          },
          octal7: {
            type: 'v',
            name: 'octal7',
            pos: [91, 50, 6],
            meta: {
              display: 'octal7',
              isDefined: true,
              canReset: false,
              usage: [[91, 50, 6]],
              docs: 'Placeholder docs for argument, keyword, or property',
              source: 'user',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0o7fff',
                  args: [],
                  meta: {},
                  value: ['0o7fff'],
                },
              ],
            },
          },
        },
      },
      main: {},
    };

    // verify results
    expect(tokenized.local).toEqual(expectedVars);

    // define expected global variables
    const expectedGlobal: GlobalTokens = [
      {
        type: 'p',
        name: 'literals',
        pos: [86, 4, 8],
        range: { start: [86, 0, 4], end: [93, 0, 3] },
        meta: {
          source: 'user',
          args: {
            byte1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '0b',
                  args: [],
                  meta: {},
                  value: ['0b'],
                },
              ],
              private: false,
              req: true,
              display: 'byte1',
              code: true,
              pos: [86, 14, 5],
            },
            byte2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '0ub',
                  args: [],
                  meta: {},
                  value: ['0ub'],
                },
              ],
              private: false,
              req: true,
              display: 'byte2',
              code: true,
              pos: [86, 21, 5],
            },
            int1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0s',
                  args: [],
                  meta: {},
                  value: ['0s'],
                },
              ],
              private: false,
              req: true,
              display: 'int1',
              code: true,
              pos: [86, 28, 4],
            },
            uint1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'UInt',
                  display: 'UInt',
                  serialized: '0u',
                  args: [],
                  meta: {},
                  value: ['0u'],
                },
              ],
              private: false,
              req: true,
              display: 'uint1',
              code: true,
              pos: [86, 34, 5],
            },
            uint2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'UInt',
                  display: 'UInt',
                  serialized: '0us',
                  args: [],
                  meta: {},
                  value: ['0us'],
                },
              ],
              private: false,
              req: true,
              display: 'uint2',
              code: true,
              pos: [86, 41, 5],
            },
            long1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Long',
                  display: 'Long',
                  serialized: '0l',
                  args: [],
                  meta: {},
                  value: ['0l'],
                },
              ],
              private: false,
              req: true,
              display: 'long1',
              code: true,
              pos: [86, 48, 5],
            },
            ulong1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'ULong',
                  display: 'ULong',
                  serialized: '0ul',
                  args: [],
                  meta: {},
                  value: ['0ul'],
                },
              ],
              private: false,
              req: true,
              display: 'ulong1',
              code: true,
              pos: [86, 55, 6],
            },
            long641: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Long64',
                  display: 'Long64',
                  serialized: '0ll',
                  args: [],
                  meta: {},
                  value: ['0ll'],
                },
              ],
              private: false,
              req: true,
              display: 'long641',
              code: true,
              pos: [86, 63, 7],
            },
            ulong641: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'ULong64',
                  display: 'ULong64',
                  serialized: '0ull',
                  args: [],
                  meta: {},
                  value: ['0ull'],
                },
              ],
              private: false,
              req: true,
              display: 'ulong641',
              code: true,
              pos: [86, 72, 8],
            },
            float1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '1.',
                  args: [],
                  meta: {},
                  value: ['1.'],
                },
              ],
              private: false,
              req: true,
              display: 'float1',
              code: true,
              pos: [87, 2, 6],
            },
            float2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '.1',
                  args: [],
                  meta: {},
                  value: ['.1'],
                },
              ],
              private: false,
              req: true,
              display: 'float2',
              code: true,
              pos: [87, 10, 6],
            },
            float3: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '1.1',
                  args: [],
                  meta: {},
                  value: ['1.1'],
                },
              ],
              private: false,
              req: true,
              display: 'float3',
              code: true,
              pos: [87, 18, 6],
            },
            float4: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10e',
                  args: [],
                  meta: {},
                  value: ['10e'],
                },
              ],
              private: false,
              req: true,
              display: 'float4',
              code: true,
              pos: [87, 26, 6],
            },
            float5: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10e5',
                  args: [],
                  meta: {},
                  value: ['10e5'],
                },
              ],
              private: false,
              req: true,
              display: 'float5',
              code: true,
              pos: [87, 34, 6],
            },
            float6: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '10.e-3',
                  args: [],
                  meta: {},
                  value: ['10.e-3'],
                },
              ],
              private: false,
              req: true,
              display: 'float6',
              code: true,
              pos: [87, 42, 6],
            },
            float7: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '.1e+12',
                  args: [],
                  meta: {},
                  value: ['.1e+12'],
                },
              ],
              private: false,
              req: true,
              display: 'float7',
              code: true,
              pos: [87, 50, 6],
            },
            float8: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Float',
                  display: 'Float',
                  serialized: '2.3e12',
                  args: [],
                  meta: {},
                  value: ['2.3e12'],
                },
              ],
              private: false,
              req: true,
              display: 'float8',
              code: true,
              pos: [87, 58, 6],
            },
            double0: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1d',
                  args: [],
                  meta: {},
                  value: ['1d'],
                },
              ],
              private: false,
              req: true,
              display: 'double0',
              code: true,
              pos: [88, 2, 7],
            },
            double1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1.d',
                  args: [],
                  meta: {},
                  value: ['1.d'],
                },
              ],
              private: false,
              req: true,
              display: 'double1',
              code: true,
              pos: [88, 11, 7],
            },
            double2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '.1d',
                  args: [],
                  meta: {},
                  value: ['.1d'],
                },
              ],
              private: false,
              req: true,
              display: 'double2',
              code: true,
              pos: [88, 20, 7],
            },
            double3: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '1.1d',
                  args: [],
                  meta: {},
                  value: ['1.1d'],
                },
              ],
              private: false,
              req: true,
              display: 'double3',
              code: true,
              pos: [88, 29, 7],
            },
            double4: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10d',
                  args: [],
                  meta: {},
                  value: ['10d'],
                },
              ],
              private: false,
              req: true,
              display: 'double4',
              code: true,
              pos: [88, 38, 7],
            },
            double5: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10d5',
                  args: [],
                  meta: {},
                  value: ['10d5'],
                },
              ],
              private: false,
              req: true,
              display: 'double5',
              code: true,
              pos: [88, 47, 7],
            },
            double6: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '10.d-3',
                  args: [],
                  meta: {},
                  value: ['10.d-3'],
                },
              ],
              private: false,
              req: true,
              display: 'double6',
              code: true,
              pos: [88, 56, 7],
            },
            double7: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '.1d+12',
                  args: [],
                  meta: {},
                  value: ['.1d+12'],
                },
              ],
              private: false,
              req: true,
              display: 'double7',
              code: true,
              pos: [88, 65, 7],
            },
            double8: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Double',
                  display: 'Double',
                  serialized: '2.3d12',
                  args: [],
                  meta: {},
                  value: ['2.3d12'],
                },
              ],
              private: false,
              req: true,
              display: 'double8',
              code: true,
              pos: [88, 74, 7],
            },
            binary1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: "'10101'b",
                  args: [],
                  meta: {},
                  value: ["'10101'b"],
                },
              ],
              private: false,
              req: true,
              display: 'binary1',
              code: true,
              pos: [89, 2, 7],
            },
            binary2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: "'10101'b",
                  args: [],
                  meta: {},
                  value: ["'10101'b"],
                },
              ],
              private: false,
              req: true,
              display: 'binary2',
              code: true,
              pos: [89, 11, 7],
            },
            hex1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'x",
                  args: [],
                  meta: {},
                  value: ["'10101'x"],
                },
              ],
              private: false,
              req: true,
              display: 'hex1',
              code: true,
              pos: [90, 2, 4],
            },
            hex2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'7fff'xs",
                  args: [],
                  meta: {},
                  value: ["'7fff'xs"],
                },
              ],
              private: false,
              req: true,
              display: 'hex2',
              code: true,
              pos: [90, 8, 4],
            },
            hex3: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'8fff'xs",
                  args: [],
                  meta: {},
                  value: ["'8fff'xs"],
                },
              ],
              private: false,
              req: true,
              display: 'hex3',
              code: true,
              pos: [90, 14, 4],
            },
            hex4: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'x",
                  args: [],
                  meta: {},
                  value: ["'10101'x"],
                },
              ],
              private: false,
              req: true,
              display: 'hex4',
              code: true,
              pos: [90, 20, 4],
            },
            hex5: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0x',
                  args: [],
                  meta: {},
                  value: ['0x'],
                },
              ],
              private: false,
              req: true,
              display: 'hex5',
              code: true,
              pos: [90, 26, 4],
            },
            hex6: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0x7fff',
                  args: [],
                  meta: {},
                  value: ['0x7fff'],
                },
              ],
              private: false,
              req: true,
              display: 'hex6',
              code: true,
              pos: [90, 32, 4],
            },
            octal1: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '"36',
                  args: [],
                  meta: {},
                  value: ['"36'],
                },
              ],
              private: false,
              req: true,
              display: 'octal1',
              code: true,
              pos: [91, 2, 6],
            },
            octal2: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Byte',
                  display: 'Byte',
                  serialized: '"36b',
                  args: [],
                  meta: {},
                  value: ['"36b'],
                },
              ],
              private: false,
              req: true,
              display: 'octal2',
              code: true,
              pos: [91, 10, 6],
            },
            octal3: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'ULong64',
                  display: 'ULong64',
                  serialized: '"345ull',
                  args: [],
                  meta: {},
                  value: ['"345ull'],
                },
              ],
              private: false,
              req: true,
              display: 'octal3',
              code: true,
              pos: [91, 18, 6],
            },
            octal4: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'o",
                  args: [],
                  meta: {},
                  value: ["'10101'o"],
                },
              ],
              private: false,
              req: true,
              display: 'octal4',
              code: true,
              pos: [91, 26, 6],
            },
            octal5: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: "'10101'o",
                  args: [],
                  meta: {},
                  value: ["'10101'o"],
                },
              ],
              private: false,
              req: true,
              display: 'octal5',
              code: true,
              pos: [91, 34, 6],
            },
            octal6: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0o',
                  args: [],
                  meta: {},
                  value: ['0o'],
                },
              ],
              private: false,
              req: true,
              display: 'octal6',
              code: true,
              pos: [91, 42, 6],
            },
            octal7: {
              docs: 'Placeholder docs for argument, keyword, or property',
              direction: 'bidirectional',
              source: 'internal',
              type: [
                {
                  name: 'Int',
                  display: 'Int',
                  serialized: '0o7fff',
                  args: [],
                  meta: {},
                  value: ['0o7fff'],
                },
              ],
              private: false,
              req: true,
              display: 'octal7',
              code: true,
              pos: [91, 50, 6],
            },
          },
          docs: "\n```idl\nliterals, byte1, byte2, int1, uint1, uint2, long1, ulong1, long641, ulong641, float1, float2, float3, float4, float5, float6, float7, float8, double0, double1, double2, double3, double4, double5, double6, double7, double8, binary1, binary2, hex1, hex2, hex3, hex4, hex5, hex6, octal1, octal2, octal3, octal4, octal5, octal6, octal7\n```\n\n\n\n\n### Arguments\n\n- **byte1**: bidirectional, required, 0b\n\n  Placeholder docs for argument, keyword, or property\n\n- **byte2**: bidirectional, required, 0ub\n\n  Placeholder docs for argument, keyword, or property\n\n- **int1**: bidirectional, required, 0s\n\n  Placeholder docs for argument, keyword, or property\n\n- **uint1**: bidirectional, required, 0u\n\n  Placeholder docs for argument, keyword, or property\n\n- **uint2**: bidirectional, required, 0us\n\n  Placeholder docs for argument, keyword, or property\n\n- **long1**: bidirectional, required, 0l\n\n  Placeholder docs for argument, keyword, or property\n\n- **ulong1**: bidirectional, required, 0ul\n\n  Placeholder docs for argument, keyword, or property\n\n- **long641**: bidirectional, required, 0ll\n\n  Placeholder docs for argument, keyword, or property\n\n- **ulong641**: bidirectional, required, 0ull\n\n  Placeholder docs for argument, keyword, or property\n\n- **float1**: bidirectional, required, 1.\n\n  Placeholder docs for argument, keyword, or property\n\n- **float2**: bidirectional, required, .1\n\n  Placeholder docs for argument, keyword, or property\n\n- **float3**: bidirectional, required, 1.1\n\n  Placeholder docs for argument, keyword, or property\n\n- **float4**: bidirectional, required, 10e\n\n  Placeholder docs for argument, keyword, or property\n\n- **float5**: bidirectional, required, 10e5\n\n  Placeholder docs for argument, keyword, or property\n\n- **float6**: bidirectional, required, 10.e-3\n\n  Placeholder docs for argument, keyword, or property\n\n- **float7**: bidirectional, required, .1e+12\n\n  Placeholder docs for argument, keyword, or property\n\n- **float8**: bidirectional, required, 2.3e12\n\n  Placeholder docs for argument, keyword, or property\n\n- **double0**: bidirectional, required, 1d\n\n  Placeholder docs for argument, keyword, or property\n\n- **double1**: bidirectional, required, 1.d\n\n  Placeholder docs for argument, keyword, or property\n\n- **double2**: bidirectional, required, .1d\n\n  Placeholder docs for argument, keyword, or property\n\n- **double3**: bidirectional, required, 1.1d\n\n  Placeholder docs for argument, keyword, or property\n\n- **double4**: bidirectional, required, 10d\n\n  Placeholder docs for argument, keyword, or property\n\n- **double5**: bidirectional, required, 10d5\n\n  Placeholder docs for argument, keyword, or property\n\n- **double6**: bidirectional, required, 10.d-3\n\n  Placeholder docs for argument, keyword, or property\n\n- **double7**: bidirectional, required, .1d+12\n\n  Placeholder docs for argument, keyword, or property\n\n- **double8**: bidirectional, required, 2.3d12\n\n  Placeholder docs for argument, keyword, or property\n\n- **binary1**: bidirectional, required, '10101'b\n\n  Placeholder docs for argument, keyword, or property\n\n- **binary2**: bidirectional, required, '10101'b\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex1**: bidirectional, required, '10101'x\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex2**: bidirectional, required, '7fff'xs\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex3**: bidirectional, required, '8fff'xs\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex4**: bidirectional, required, '10101'x\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex5**: bidirectional, required, 0x\n\n  Placeholder docs for argument, keyword, or property\n\n- **hex6**: bidirectional, required, 0x7fff\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal1**: bidirectional, required, \"36\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal2**: bidirectional, required, \"36b\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal3**: bidirectional, required, \"345ull\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal4**: bidirectional, required, '10101'o\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal5**: bidirectional, required, '10101'o\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal6**: bidirectional, required, 0o\n\n  Placeholder docs for argument, keyword, or property\n\n- **octal7**: bidirectional, required, 0o7fff\n\n  Placeholder docs for argument, keyword, or property\n\n",
          docsLookup: { default: '' },
          display: 'literals',
          kws: {},
          private: false,
          struct: [],
        },
        file: 'not-real',
      },
    ];

    // verify results
    expect(tokenized.global).toEqual(expectedGlobal);

    // define expected compile options
    const expectedCompile: ICompileOptions = {
      func: {},
      pro: { literals: ['idl2'] },
      main: [],
    };

    // verify results
    expect(tokenized.compile).toEqual(expectedCompile);
  });
});
