import { Assembler } from '@idl/assembler';
import { CancellationToken } from '@idl/cancellation-tokens';
import { LogManager } from '@idl/logger';
import { GetTokenNames } from '@idl/parser';
import { IDL_INDEX_OPTIONS, IDLIndex } from '@idl/parsing/index';
import { SyntaxProblems } from '@idl/types/problem-codes';

IDL_INDEX_OPTIONS.IS_TEST = true;

describe(`[auto generated] Verify number literal serialization`, () => {
  it(`[auto generated] matches what we parsed`, async () => {
    // create index
    const index = new IDLIndex(
      new LogManager({
        alert: () => {
          // do nothing
        },
      }),
      0
    );

    // test code to extract tokens from
    const code = [
      `;+`,
      `; :Arguments:`,
      `;   byte1: bidirectional, required, 0b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   byte2: bidirectional, required, 0ub`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   int1: bidirectional, required, 0s`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   uint1: bidirectional, required, 0u`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   uint2: bidirectional, required, 0us`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   long1: bidirectional, required, 0l`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   ulong1: bidirectional, required, 0ul`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   long641: bidirectional, required, 0ll`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   ulong641: bidirectional, required, 0ull`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float1: bidirectional, required, 1.`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float2: bidirectional, required, .1`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float3: bidirectional, required, 1.1`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float4: bidirectional, required, 10e`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float5: bidirectional, required, 10e5`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float6: bidirectional, required, 10.e-3`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float7: bidirectional, required, .1e+12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   float8: bidirectional, required, 2.3e12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double0: bidirectional, required, 1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double1: bidirectional, required, 1.d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double2: bidirectional, required, .1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double3: bidirectional, required, 1.1d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double4: bidirectional, required, 10d`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double5: bidirectional, required, 10d5`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double6: bidirectional, required, 10.d-3`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double7: bidirectional, required, .1d+12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   double8: bidirectional, required, 2.3d12`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   binary1: bidirectional, required, '10101'b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   binary2: bidirectional, required, '10101'b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex1: bidirectional, required, '10101'x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex2: bidirectional, required, '7fff'xs`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex3: bidirectional, required, '8fff'xs`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex4: bidirectional, required, '10101'x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex5: bidirectional, required, 0x`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   hex6: bidirectional, required, 0x7fff`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal1: bidirectional, required, "36`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal2: bidirectional, required, "36b`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal3: bidirectional, required, "345ull`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal4: bidirectional, required, '10101'o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal5: bidirectional, required, '10101'o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal6: bidirectional, required, 0o`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;   octal7: bidirectional, required, 0o7fff`,
      `;     Placeholder docs for argument, keyword, or property`,
      `;`,
      `;-`,
      `pro literals, byte1, byte2, int1, uint1, uint2, long1, ulong1, long641, ulong641, $`,
      `  float1, float2, float3, float4, float5, float6, float7, float8, $`,
      `  double0, double1, double2, double3, double4, double5, double6, double7, double8, $`,
      `  binary1, binary2, $`,
      `  hex1, hex2, hex3, hex4, hex5, hex6, $`,
      `  octal1, octal2, octal3, octal4, octal5, octal6, octal7`,
      `  compile_opt idl2`,
      `end`,
      ``,
    ];

    // extract tokens
    const tokenized = await index.getParsedProCode(
      'my_file.pro',
      code,
      new CancellationToken(),
      { postProcess: true }
    );

    // extract token names
    const tokenizedNames = GetTokenNames(tokenized);

    // format code
    const formatted = Assembler(tokenized, new CancellationToken(), {
      autoDoc: true,
      autoFix: false,
      formatter: 'fiddle',
    });

    // verify formatting
    if (formatted === undefined) {
      expect(formatted).toEqual(undefined);
    } else {
      // define expected problems
      const expectedFormatting: string[] = [
        `;+`,
        `; :Arguments:`,
        `;   byte1: bidirectional, required, 0b`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   byte2: bidirectional, required, 0ub`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   int1: bidirectional, required, 0s`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   uint1: bidirectional, required, 0u`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   uint2: bidirectional, required, 0us`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   long1: bidirectional, required, 0l`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   ulong1: bidirectional, required, 0ul`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   long641: bidirectional, required, 0ll`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   ulong641: bidirectional, required, 0ull`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float1: bidirectional, required, 1.`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float2: bidirectional, required, .1`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float3: bidirectional, required, 1.1`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float4: bidirectional, required, 10e`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float5: bidirectional, required, 10e5`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float6: bidirectional, required, 10.e-3`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float7: bidirectional, required, .1e+12`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   float8: bidirectional, required, 2.3e12`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double0: bidirectional, required, 1d`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double1: bidirectional, required, 1.d`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double2: bidirectional, required, .1d`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double3: bidirectional, required, 1.1d`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double4: bidirectional, required, 10d`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double5: bidirectional, required, 10d5`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double6: bidirectional, required, 10.d-3`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double7: bidirectional, required, .1d+12`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   double8: bidirectional, required, 2.3d12`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   binary1: bidirectional, required, '10101'b`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   binary2: bidirectional, required, '10101'b`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex1: bidirectional, required, '10101'x`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex2: bidirectional, required, '7fff'xs`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex3: bidirectional, required, '8fff'xs`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex4: bidirectional, required, '10101'x`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex5: bidirectional, required, 0x`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   hex6: bidirectional, required, 0x7fff`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal1: bidirectional, required, "36`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal2: bidirectional, required, "36b`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal3: bidirectional, required, "345ull`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal4: bidirectional, required, '10101'o`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal5: bidirectional, required, '10101'o`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal6: bidirectional, required, 0o`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;   octal7: bidirectional, required, 0o7fff`,
        `;     Placeholder docs for argument, keyword, or property`,
        `;`,
        `;-`,
        `pro literals, byte1, byte2, int1, uint1, uint2, long1, ulong1, long641, ulong641, $`,
        `  float1, float2, float3, float4, float5, float6, float7, float8, $`,
        `  double0, double1, double2, double3, double4, double5, double6, double7, double8, $`,
        `  binary1, binary2, $`,
        `  hex1, hex2, hex3, hex4, hex5, hex6, $`,
        `  octal1, octal2, octal3, octal4, octal5, octal6, octal7`,
        `  compile_opt idl2`,
        `end`,
        ``,
      ];

      // verify formatting
      expect(formatted.split(`\n`)).toEqual(expectedFormatting);

      // parse formatted code
      const reParsed = await index.getParsedProCode(
        'my_file.pro',
        formatted,
        new CancellationToken(),
        { postProcess: true }
      );

      // make sure the syntax trees are the same as they were before if not def files
      if (tokenized.type !== 'def') {
        expect(GetTokenNames(reParsed)).toEqual(tokenizedNames);
      }
    }

    // define expected problems
    const expectedProblems: SyntaxProblems = [
      {
        code: 104,
        info: 'Unused variable "byte1"',
        start: [86, 14, 5],
        end: [86, 14, 5],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "byte2"',
        start: [86, 21, 5],
        end: [86, 21, 5],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "int1"',
        start: [86, 28, 4],
        end: [86, 28, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "uint1"',
        start: [86, 34, 5],
        end: [86, 34, 5],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "uint2"',
        start: [86, 41, 5],
        end: [86, 41, 5],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "long1"',
        start: [86, 48, 5],
        end: [86, 48, 5],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "ulong1"',
        start: [86, 55, 6],
        end: [86, 55, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "long641"',
        start: [86, 63, 7],
        end: [86, 63, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "ulong641"',
        start: [86, 72, 8],
        end: [86, 72, 8],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float1"',
        start: [87, 2, 6],
        end: [87, 2, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float2"',
        start: [87, 10, 6],
        end: [87, 10, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float3"',
        start: [87, 18, 6],
        end: [87, 18, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float4"',
        start: [87, 26, 6],
        end: [87, 26, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float5"',
        start: [87, 34, 6],
        end: [87, 34, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float6"',
        start: [87, 42, 6],
        end: [87, 42, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float7"',
        start: [87, 50, 6],
        end: [87, 50, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "float8"',
        start: [87, 58, 6],
        end: [87, 58, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double0"',
        start: [88, 2, 7],
        end: [88, 2, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double1"',
        start: [88, 11, 7],
        end: [88, 11, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double2"',
        start: [88, 20, 7],
        end: [88, 20, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double3"',
        start: [88, 29, 7],
        end: [88, 29, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double4"',
        start: [88, 38, 7],
        end: [88, 38, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double5"',
        start: [88, 47, 7],
        end: [88, 47, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double6"',
        start: [88, 56, 7],
        end: [88, 56, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double7"',
        start: [88, 65, 7],
        end: [88, 65, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "double8"',
        start: [88, 74, 7],
        end: [88, 74, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "binary1"',
        start: [89, 2, 7],
        end: [89, 2, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "binary2"',
        start: [89, 11, 7],
        end: [89, 11, 7],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex1"',
        start: [90, 2, 4],
        end: [90, 2, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex2"',
        start: [90, 8, 4],
        end: [90, 8, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex3"',
        start: [90, 14, 4],
        end: [90, 14, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex4"',
        start: [90, 20, 4],
        end: [90, 20, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex5"',
        start: [90, 26, 4],
        end: [90, 26, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "hex6"',
        start: [90, 32, 4],
        end: [90, 32, 4],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal1"',
        start: [91, 2, 6],
        end: [91, 2, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal2"',
        start: [91, 10, 6],
        end: [91, 10, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal3"',
        start: [91, 18, 6],
        end: [91, 18, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal4"',
        start: [91, 26, 6],
        end: [91, 26, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal5"',
        start: [91, 34, 6],
        end: [91, 34, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal6"',
        start: [91, 42, 6],
        end: [91, 42, 6],
        canReport: true,
      },
      {
        code: 104,
        info: 'Unused variable "octal7"',
        start: [91, 50, 6],
        end: [91, 50, 6],
        canReport: true,
      },
    ];

    // verify problems
    expect(
      tokenized.parseProblems.concat(tokenized.postProcessProblems)
    ).toEqual(expectedProblems);
  });
});
