import { IDL_PROBLEM_CODES } from './idl-problem-codes.interface';

/** When a problem is a hint */
export type IDLHintLevel = 'hint';
/** When a problem is informational */
export type IDLInformationLevel = 'info';
/** When a problem is a warning */
export type IDLWarningLevel = 'warning';
/** When a problem is an error */
export type IDLErrorLevel = 'error';

/**
 * Union type of all allowed severity levels
 */
export type IDLProblemSeverity =
  | IDLHintLevel
  | IDLInformationLevel
  | IDLWarningLevel
  | IDLErrorLevel;

/**
 * Strictly typed lookup of problem severity
 */
interface IDLProblemSeverityLookup {
  /** When a problem is a hint */
  HINT: IDLHintLevel;
  /** When a problem is informational */
  INFORMATION: IDLInformationLevel;
  /** When a problem is a warning */
  WARNING: IDLWarningLevel;
  /** When a problem is an error */
  ERROR: IDLErrorLevel;
}

/**
 * Lookup containing the types/values for different problem severity levels
 */
export const IDL_PROBLEM_SEVERITY_LOOKUP: IDLProblemSeverityLookup = {
  HINT: 'hint',
  INFORMATION: 'info',
  WARNING: 'warning',
  ERROR: 'error',
};

/**
 * Maps IDL problem codes to a severity level.
 *
 * If a value is not in the map, then it is assumed that we have an error level.
 */
export const IDL_PROBLEM_SEVERITY_LEVEL_MAP: {
  [key: number]: IDLProblemSeverity;
} = {};

/**
 * Add any problem codes that are informational
 */
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.TODO] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.ARGS_MISSING_FROM_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.NO_ARGS_TO_DOCUMENT] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.KEYWORDS_MISSING_FROM_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.NO_KEYWORDS_TO_DOCUMENT] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.RETURNS_MISSING_FROM_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.INVALID_IN_OUT_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.INVALID_REQUIRED_OPTIONAL_DOCS
] = IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.INVALID_TYPE_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.INVALID_PRIVATE_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.NOT_ENOUGH_DOCS_PARAMETERS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.TOO_MANY_DOCS_PARAMETERS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DOCS_NOT_LEFT_ALIGNED] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.RETURN_DOCS_MISSING_TYPE] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.RETURN_DOCS_INVALID] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.RETURN_DOCS_NOT_NEEDED] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.DOCUMENTED_PARAMETER_DOESNT_EXIST
] = IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.PARAMETER_IS_MISSING_FROM_DOCS
] = IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.MISSING_STRUCTURE_FROM_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.PROPERTY_MISSING_FROM_DOCS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.NOT_ENOUGH_PROPERTY_DOCS_PARAMETERS
] = IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.TOO_MANY_PROPERTY_DOCS_PARAMETERS
] = IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.UNKNOWN_DISABLED_ALIAS] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.IMPLIED_PRINT_NOTEBOOK] =
  IDL_PROBLEM_SEVERITY_LOOKUP.INFORMATION;

/**
 * Add any problem codes that are warnings
 */
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.ARGS_FIRST] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_FUNCTION] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_FUNCTION_METHOD] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_PROCEDURE] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_PROCEDURE_METHOD] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_STRUCTURE] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.DUPLICATE_SYSTEM_VARIABLE] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.USE_IDL2_COMPILE_OPT] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.POTENTIAL_TYPE_INCOMPATIBILITIES
] = IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.POTENTIAL_IDL_ARRAY_TYPE_INCOMPATIBILITIES
] = IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.POTENTIALLY_UNDEFINED_VAR] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[
  IDL_PROBLEM_CODES.POTENTIAL_VAR_USAGE_BEFORE_DEF
] = IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
IDL_PROBLEM_SEVERITY_LEVEL_MAP[IDL_PROBLEM_CODES.UNUSED_VARIABLE] =
  IDL_PROBLEM_SEVERITY_LOOKUP.WARNING;
