import { IDL_PROBLEM_CODES } from './idl-problem-codes.interface';

/**
 * Lookup containing problem codes that users are allowed to turn off.
 *
 * Limited to non-fatal error problem codes that will prevent IDL from compiling code
 */
export const TOGGLEABLE_PROBLEM_CODES: { [key: number]: boolean } = {};

// code for compile_opt statements
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.NO_COMPILE_OPT] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.NO_COMPILE_OPT_IDL2] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.USE_IDL2_COMPILE_OPT] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.ARGS_FIRST] = true;

// codes for documentation related problems
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.ARGS_MISSING_FROM_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.NO_ARGS_TO_DOCUMENT] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.KEYWORDS_MISSING_FROM_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.NO_KEYWORDS_TO_DOCUMENT] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.RETURNS_MISSING_FROM_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.INVALID_IN_OUT_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.INVALID_REQUIRED_OPTIONAL_DOCS] =
  true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.INVALID_TYPE_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.INVALID_PRIVATE_DOCS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.NOT_ENOUGH_DOCS_PARAMETERS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.TOO_MANY_DOCS_PARAMETERS] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.DOCS_NOT_LEFT_ALIGNED] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.RETURN_DOCS_MISSING_TYPE] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.RETURN_DOCS_INVALID] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.RETURN_DOCS_NOT_NEEDED] = true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.DOCUMENTED_PARAMETER_DOESNT_EXIST] =
  true;
TOGGLEABLE_PROBLEM_CODES[IDL_PROBLEM_CODES.PARAMETER_IS_MISSING_FROM_DOCS] =
  true;
