<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>idl-log</string>
    <key>scopeName</key>
    <string>source.idl-log</string>
    <key>comment</key>
    <string>Generated automatically during the extension build process from YAML</string>
    <key>uuid</key>
    <string>ade03939-fbcb-4b3a-9ad2-bc531c6bbed8</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#log_line_debug</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#log_line_start</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#all_tokens</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>all_tokens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#quote_tokens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#links</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#special</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#grouper_tokens</string>
          </dict>
        </array>
      </dict>
      <key>grouper_tokens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#structure</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bracket_square</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#bracket_paren</string>
          </dict>
        </array>
      </dict>
      <key>quote_tokens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#quote_double</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#quote_single</string>
          </dict>
        </array>
      </dict>
      <key>bracket_square</key>
      <dict>
        <key>name</key>
        <string>group.brackets.square.idl</string>
        <key>begin</key>
        <string>(?i)\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.idl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?i)\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.square.idl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all_tokens</string>
          </dict>
        </array>
      </dict>
      <key>bracket_paren</key>
      <dict>
        <key>name</key>
        <string>group.brackets.paren.idl</string>
        <key>begin</key>
        <string>(?i)\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.idl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?i)\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.round.idl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all_tokens</string>
          </dict>
        </array>
      </dict>
      <key>log_type</key>
      <dict>
        <key>name</key>
        <string>variable.other.constant.object.ts</string>
        <key>match</key>
        <string>(?i)[a-z_\-0-9]+</string>
      </dict>
      <key>log_line_debug</key>
      <dict>
        <key>name</key>
        <string>variable.other.readwrite.ts.idl</string>
        <key>match</key>
        <string>(?i)^(idl) (input) (.*)$</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.primitive.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#log_type</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.idl</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>log_line_start</key>
      <dict>
        <key>name</key>
        <string>variable.other.readwrite.ts.idl</string>
        <key>match</key>
        <string>(?i)^(idl[a-z_\-0-9]*)\s*([a-z_\-0-9]+)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.primitive.ts</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#log_type</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>links</key>
      <dict>
        <key>name</key>
        <string>markup.underline</string>
        <key>match</key>
        <string>(?i)(?:(?:https?|ftp|file|ws):\/\/|www\.|ftp\.)(?:\([-A-Z0-9+&amp;@#/%=~_|$?!:,.]*\)|[-A-Z0-9+&amp;@#/%=~_|$?!:,.])*(?:\([-A-Z0-9+&amp;@#/%=~_|$?!:,.]*\)|[A-Z0-9+&amp;@#/%=~_|$])</string>
      </dict>
      <key>numbers</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.idl</string>
        <key>match</key>
        <string>(?i)(?&lt;![a-z_$])(0[box][a-z0-9]*|[0-9.]+((e|d)-?[0-9]*|[a-z]*))(?:i|j)?</string>
      </dict>
      <key>quote_double</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.idl</string>
        <key>begin</key>
        <string>(?i)"</string>
        <key>end</key>
        <string>(?i)$|(?&lt;!")"(?!")</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#quote_escape</string>
          </dict>
        </array>
      </dict>
      <key>quote_escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.idl</string>
        <key>match</key>
        <string>(?i)\r|\n</string>
      </dict>
      <key>quote_single</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.idl</string>
        <key>begin</key>
        <string>(?i)'</string>
        <key>end</key>
        <string>(?i)$|(?&lt;!')'(?!')</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#quote_escape</string>
          </dict>
        </array>
      </dict>
      <key>special</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.idl</string>
        <key>match</key>
        <string>(?i)\b(?:true|false|null|undefined|void)\b</string>
      </dict>
      <key>structure_property</key>
      <dict>
        <key>begin</key>
        <string>(?i)([a-z0-9_$]*\s*):</string>
        <key>end</key>
        <string>(?i)(?=\buntil\b|\belse\b|\bthen\b|\bdo\b|\bof\b|\)|\]|\}|,|;)|(?=(?&lt;!&amp;)&amp;(?!&amp;))|(?&lt;!\$\s*|\$\s*;.*)$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.idl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all_tokens</string>
          </dict>
        </array>
      </dict>
      <key>structure_property_string</key>
      <dict>
        <key>begin</key>
        <string>(?i)(['"].*):\s</string>
        <key>end</key>
        <string>(?i)(?=\buntil\b|\belse\b|\bthen\b|\bdo\b|\bof\b|\)|\]|\}|,|;)|(?=(?&lt;!&amp;)&amp;(?!&amp;))|(?&lt;!\$\s*|\$\s*;.*)$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.quoted.single.idl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#all_tokens</string>
          </dict>
        </array>
      </dict>
      <key>structure</key>
      <dict>
        <key>name</key>
        <string>group.structure.idl</string>
        <key>begin</key>
        <string>(?i){</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.idl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?i)}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.brace.idl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#structure_property_string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#structure_property</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>