import { IDL_TYPE_LOOKUP } from '@idl/data-types/core';

/**
 * Order of our types in appearance of priority
 */
export const ALLOWED_TYPES_AS_INDEX: { [key: string]: any } = {};
// ALLOWED_INDEX_TYPES[IDL_TYPE_LOOKUP.COMPLEX_NUMBER] = true;
// ALLOWED_INDEX_TYPES[IDL_TYPE_LOOKUP.COMPLEX_DOUBLE] = true;
// ALLOWED_INDEX_TYPES[IDL_TYPE_LOOKUP.COMPLEX_FLOAT] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.NUMBER] = true;
// ALLOWED_INDEX_TYPES[IDL_TYPE_LOOKUP.BIG_INTEGER] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.DOUBLE] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.FLOAT] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.UNSIGNED_LONG64] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.LONG64] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.UNSIGNED_LONG] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.LONG] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.UNSIGNED_INTEGER] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.INTEGER] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.BYTE] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.BOOLEAN] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.STRING] = true;
ALLOWED_TYPES_AS_INDEX[IDL_TYPE_LOOKUP.ARRAY] = true;

/**
 * IDL types that we can index
 */
export const ALLOWED_TO_INDEX: { [key: string]: any } = {};
ALLOWED_TO_INDEX[IDL_TYPE_LOOKUP.ARRAY] = true;
ALLOWED_TO_INDEX[IDL_TYPE_LOOKUP.HASH] = true;
ALLOWED_TO_INDEX[IDL_TYPE_LOOKUP.ORDERED_HASH] = true;
ALLOWED_TO_INDEX[IDL_TYPE_LOOKUP.DICTIONARY] = true;
ALLOWED_TO_INDEX[IDL_TYPE_LOOKUP.LIST] = true;
